#!/usr/bin/env python3
"""
Generator for the Alif Laam Meem Jewellers website.

Every .html file in this folder is produced by this script. Edit the content
here (SITE, PRODUCTS, TESTIMONIALS, the page_* functions), then run:

    python3 build.py

Why a generator: the site is 24 pages with a shared header, footer and
catalogue. Keeping one source of truth means a change to the phone number or
a product price updates every page that mentions it.

Output: index.html, about.html, collections.html, atelier.html,
        appointment.html, clients.html, visit.html, privacy.html, terms.html,
        piece-<id>.html for every product.
"""

import html
import json
import os
from urllib.parse import quote

BUILD_NOTE = "<!-- Generated by build.py — edit build.py then run: python3 build.py -->"
HERE = os.path.dirname(os.path.abspath(__file__))

# Drop your own photograph into assets/ and it is picked up on the next build.
# Any of these names works; the first match wins. Recommended: a wide image,
# at least 2000px across, that reads well with a dark scrim over it.
HERO_IMAGE_NAMES = ("hero.jpg", "hero.jpeg", "hero.png", "hero.webp", "hero.avif")


def find_hero_image():
    """Path to the hero background image, or None if none has been added."""
    for name in HERO_IMAGE_NAMES:
        if os.path.exists(os.path.join(HERE, "assets", name)):
            return "assets/" + name
    return None


# Your own logo. Drop the file into assets/ and it is picked up on the next
# build; any of these names works, the first match wins. SVG is ideal — sharp
# at every size and only a few KB — but a transparent PNG at 2x is fine too.
LOGO_FILE_NAMES = ("logo.svg", "logo.png", "logo.webp", "logo.jpg",
                   "logo.jpeg", "logo.avif")

# A square version of the mark, used for the browser tab. Optional: if it is
# missing the logo above is used instead, which is only a good idea when the
# logo is already close to square. Any of these names works.
LOGO_ICON_NAMES = ("logo-icon.svg", "logo-icon.png", "logo-icon.webp",
                   "logo-icon.jpg", "logo-icon.jpeg", "logo-icon.avif")

# How your logo is laid out in the header and footer:
#   "lockup" — the file is the complete logo: mark *and* name together. The
#              words "Alif Laam Meem / Jewellers" are dropped, because they are
#              already inside your artwork.
#   "mark"   — the file is the symbol only. It replaces the ALM square and the
#              name stays as live text beside it.
LOGO_MODE = "lockup"


def find_logo_file(names):
    """First matching file in assets/ from `names`, or None."""
    for name in names:
        if os.path.exists(os.path.join(HERE, "assets", name)):
            return "assets/" + name
    return None


LOGO_FILE = find_logo_file(LOGO_FILE_NAMES)

MIME_BY_EXT = {
    ".svg": "image/svg+xml",
    ".png": "image/png",
    ".webp": "image/webp",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".avif": "image/avif",
}


def mime_of(path):
    return MIME_BY_EXT.get(os.path.splitext(path)[1].lower(), "")

# ---------------------------------------------------------------------------
# 1. BUSINESS DETAILS
# ---------------------------------------------------------------------------
SITE = {
    "name": "Alif Laam Meem Jewellers",
    "short": "Alif Laam Meem",
    "whatsapp": "923000000000",           # digits only, international format
    "phone_display": "+92 300 000 0000",
    "email": "care@aliflaammeemjewellers.com",
    "address_1": "Shop 42, Gold Souk, Liberty Market",
    "address_2": "Gulberg III, Lahore 54660, Pakistan",
    "hours_week": "Mon – Sat · 11:00 AM – 9:00 PM",
    "hours_sun": "Sunday · 1:00 PM – 7:00 PM",
    "maps": "https://maps.google.com/?q=Liberty+Market+Gulberg+III+Lahore",
    "instagram": "https://instagram.com/",
    "facebook": "https://facebook.com/",
    "youtube": "https://youtube.com/",
}

TAGLINE = "Fine gold, diamond and polki jewellery, made to order in Lahore."


def wa(message):
    """Full WhatsApp link with a pre-written message."""
    return "https://wa.me/%s?text=%s" % (SITE["whatsapp"], quote(message))


def wa_general():
    return wa("Assalam-o-Alaikum, %s. I would like to ask about your jewellery collections."
              % SITE["name"])


# ---------------------------------------------------------------------------
# 2. ICONS + MOTIFS  (inline SVG, no image files)
# ---------------------------------------------------------------------------
def _svg(path, w="1.7", extra=""):
    return ('<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="%s" %s'
            'aria-hidden="true">%s</svg>' % (w, extra, path))


ICON = {
    "phone": _svg('<path d="M4.5 5.5c0 8 7 14 14 14l1.5-3-4-2-2 1.5c-2.5-1-5-3.5-6-6L9.5 8l-2-4-3 1.5z"/>'),
    "pin": _svg('<path d="M12 21s-7-5.6-7-11a7 7 0 1 1 14 0c0 5.4-7 11-7 11z"/><circle cx="12" cy="10" r="2.6"/>'),
    "mail": _svg('<rect x="3" y="5" width="18" height="14" rx="2.5"/><path d="M3.5 7l8.5 6 8.5-6"/>'),
    "clock": _svg('<circle cx="12" cy="12" r="8.5"/><path d="M12 7.5V12l3 2"/>'),
    "route": _svg('<path d="M19 4v7a4 4 0 0 1-4 4H5"/><path d="M8 12l-3 3 3 3"/><path d="M19 4h-4"/>'),
    "arrow": _svg('<path d="M5 12h14M13 6l6 6-6 6"/>', "2"),
    "chev": _svg('<path d="M9 6l6 6-6 6"/>', "2.4"),
    "down": _svg('<path d="M6 9l6 6 6-6"/>', "1.8"),
    "wa": _svg('<path d="M20 11.5a8 8 0 0 1-11.8 7L4 20l1.5-4A8 8 0 1 1 20 11.5z"/><path d="M8.5 9.5c0 3.2 2.8 6 6 6"/>'),
    "heart": _svg('<path d="M12 20s-7-4.4-7-9.4A4.1 4.1 0 0 1 12 7.6a4.1 4.1 0 0 1 7 3c0 5-7 9.4-7 9.4z"/>', "1.6"),
    "star": '<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 2.6l2.9 5.9 6.5.95-4.7 4.6 1.1 6.45L12 17.45 6.2 20.5l1.1-6.45-4.7-4.6 6.5-.95L12 2.6z"/></svg>',
    "starline": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M12 2.6l2.9 5.9 6.5.95-4.7 4.6 1.1 6.45L12 17.45 6.2 20.5l1.1-6.45-4.7-4.6 6.5-.95L12 2.6z"/></svg>',
    "gem": '<i class="gem"></i>',
    "instagram": _svg('<rect x="3.5" y="3.5" width="17" height="17" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17" cy="7" r="1.1" fill="currentColor" stroke="none"/>', "1.6"),
    "facebook": _svg('<path d="M14.5 8.5h2.5V5.5h-2.5c-2 0-3.5 1.6-3.5 3.5v2H9v3h2v6.5h3V14h2.5l.5-3H14V9.5c0-.6.3-1 .5-1z"/>', "1.6"),
    "youtube": _svg('<rect x="3" y="6" width="18" height="12" rx="3.5"/><path d="M11 9.8l4 2.2-4 2.2z" fill="currentColor" stroke="none"/>', "1.6"),
    "chat": _svg('<path d="M21 12a8 8 0 0 1-8 8H7l-4 3v-6a9 9 0 1 1 18-5z"/>'),
    "bench": _svg('<path d="M11 3.5l5 5-8 8H3.5v-4.5z"/><path d="M16 8.5l3 3-4 4-3-3"/><path d="M13 21h8"/>'),
    "shield": _svg('<path d="M12 3l7 3v6c0 4.2-3 8.2-7 9-4-.8-7-4.8-7-9V6z"/><path d="M9 12.2l2.2 2.2 4.3-4.4"/>'),
    "scale": _svg('<path d="M12 3v18M5 8l7-5 7 5"/><path d="M4 21h16"/>'),
    "check": _svg('<path d="M20 6.5L9.5 17 4 11.5"/>', "2.2"),
    "sketch": _svg('<path d="M15 3.5l5.5 5.5L8 21.5H2.5V16z"/><path d="M13 5.5l5.5 5.5"/>'),
}

_GS = 'stroke="url(#goldStroke)" stroke-width="2.1" fill="none" stroke-linecap="round" stroke-linejoin="round"'
_GF = 'fill="url(#goldFill)"'
_GSD = _GS.replace("goldStroke", "goldStrokeDark").replace('stroke-width="2.1"', 'stroke-width="2.6"')
_GFD = _GF.replace("goldFill", "goldFillDark")

MOTIF = {
    "rings": f'''<svg class="motif" viewBox="0 0 120 120" role="img" aria-label="Gold ring line drawing">
      <circle cx="60" cy="74" r="30" {_GS}/>
      <circle cx="60" cy="74" r="23" {_GS} stroke-width="1.1" opacity=".55"/>
      <path d="M60 26 L71 40 L60 54 L49 40 Z" {_GS}/>
      <path d="M49 40 h22 M60 26 v28" {_GS} stroke-width="1.1" opacity=".6"/>
    </svg>''',
    "necklace": f'''<svg class="motif" viewBox="0 0 120 120" role="img" aria-label="Gold necklace line drawing">
      <path d="M22 16 C22 62 34 78 60 78 C86 78 98 62 98 16" {_GS}/>
      <circle cx="22" cy="16" r="3" {_GF}/><circle cx="98" cy="16" r="3" {_GF}/>
      <path d="M60 78 v14" {_GS}/>
      <path d="M60 92 L70 104 L60 116 L50 104 Z" {_GS}/>
      <path d="M50 104 h20" {_GS} stroke-width="1.1" opacity=".6"/>
    </svg>''',
    "earrings": f'''<svg class="motif" viewBox="0 0 120 120" role="img" aria-label="Gold earrings line drawing">
      <circle cx="36" cy="16" r="5" {_GS}/><path d="M36 21 v10" {_GS}/>
      <path d="M36 31 c-13 0 -20 9 -20 19 h40 c0 -10 -7 -19 -20 -19 z" {_GS}/>
      <path d="M16 50 h40" {_GS} stroke-width="1.2"/>
      <circle cx="24" cy="58" r="3.4" {_GF}/><circle cx="36" cy="62" r="3.4" {_GF}/><circle cx="48" cy="58" r="3.4" {_GF}/>
      <circle cx="84" cy="16" r="5" {_GS}/><path d="M84 21 v10" {_GS}/>
      <path d="M84 31 c-13 0 -20 9 -20 19 h40 c0 -10 -7 -19 -20 -19 z" {_GS}/>
      <path d="M64 50 h40" {_GS} stroke-width="1.2"/>
      <circle cx="72" cy="58" r="3.4" {_GF}/><circle cx="84" cy="62" r="3.4" {_GF}/><circle cx="96" cy="58" r="3.4" {_GF}/>
    </svg>''',
    "bangles": f'''<svg class="motif" viewBox="0 0 120 120" role="img" aria-label="Gold bangles line drawing">
      <ellipse cx="60" cy="32" rx="34" ry="12" {_GS}/><ellipse cx="60" cy="52" rx="34" ry="12" {_GS}/>
      <ellipse cx="60" cy="72" rx="34" ry="12" {_GS}/><ellipse cx="60" cy="92" rx="34" ry="12" {_GS}/>
      <path d="M26 32 v60 M94 32 v60" {_GS} stroke-width="1" opacity=".28"/>
    </svg>''',
    "bridal": f'''<svg class="motif" viewBox="0 0 120 120" role="img" aria-label="Bridal set line drawing">
      <path d="M14 22 C14 60 30 74 60 74 C90 74 106 60 106 22" {_GS}/>
      <path d="M24 22 C24 52 38 64 60 64 C82 64 96 52 96 22" {_GS} stroke-width="1.1" opacity=".5"/>
      <path d="M40 52 c0 0 4 6 4 10 a4 4 0 0 1 -8 0 c0 -4 4 -10 4 -10 z" {_GF}/>
      <path d="M60 60 c0 0 4 6 4 10 a4 4 0 0 1 -8 0 c0 -4 4 -10 4 -10 z" {_GF}/>
      <path d="M80 52 c0 0 4 6 4 10 a4 4 0 0 1 -8 0 c0 -4 4 -10 4 -10 z" {_GF}/>
      <path d="M60 74 v10" {_GS} stroke-width="1.2"/>
      <path d="M60 84 L68 96 L60 108 L52 96 Z" {_GS}/>
    </svg>''',
    "pendants": f'''<svg class="motif" viewBox="0 0 120 120" role="img" aria-label="Diamond pendant line drawing">
      <circle cx="60" cy="60" r="34" {_GS} stroke-width="1.1" opacity=".35" stroke-dasharray="4 6"/>
      <path d="M60 24 L74 44 L60 64 L46 44 Z" {_GS}/>
      <path d="M46 44 h28 M60 24 v40" {_GS} stroke-width="1.1" opacity=".6"/>
      <path d="M60 64 v20" {_GS} stroke-width="1.4"/><path d="M46 92 h28" {_GS} stroke-width="1.4"/>
    </svg>''',
}


def motif_dark(kind):
    """Same line drawing in the brighter gold, for dark bands."""
    return MOTIF[kind].replace("goldStroke", "goldStrokeDark").replace("goldFill", "goldFillDark")


# ---------------------------------------------------------------------------
# 3. CATALOGUE
# ---------------------------------------------------------------------------
METALS = {
    "gold22": "22K Gold", "gold18": "18K Gold", "rose": "Rose Gold",
    "white": "White Gold", "plat": "Platinum",
}
OCCASIONS = {
    "bridal": "Bridal", "engagement": "Engagement", "festive": "Festive",
    "everyday": "Everyday", "gifting": "Gifting", "investment": "Investment",
}
TYPES = {
    "rings": "Rings", "necklace": "Necklaces", "earrings": "Earrings",
    "bangles": "Bangles", "bridal": "Bridal Sets",
}

# How many catalogue cards are visible before the visitor scrolls for more.
# Must stay in step with REVEAL_BATCH in script.js.
REVEAL_BATCH = 6

PRODUCTS = [
    dict(id="meher", name="Meher Solitaire Ring", type="rings", metals=["gold22"], occasion="engagement",
         motif="rings", badge="Bestseller", featured=True, price="PKR 385,000", note="incl. making",
         desc="A brilliant-cut solitaire raised on a hand-forged 22K band.",
         story="Set in a six-claw mount so light reaches the stone from every angle, on a band "
               "forged and filed by hand rather than cast. Choose the stone from the tray, then we "
               "size the band to the wearer.",
         tags=["BIS Hallmarked", "IGI Certified"],
         specs=[("Metal", "22K yellow gold"), ("Stone", "Brilliant-cut solitaire"), ("Setting", "Six-claw, hand-finished"),
                ("Sizing", "Sized to the wearer")]),
    dict(id="aab", name="Aab Diamond Pendant", type="necklace", metals=["gold18"], occasion="gifting",
         motif="pendants", price="PKR 168,000", note="chain included",
         desc="Pear-cut diamond suspended on a whisper-fine 18K chain.",
         story="A single pear-cut stone on the finest chain we can safely make, so the pendant "
               "moves with the wearer rather than sitting flat.",
         tags=["IGI Certified", "18K"],
         specs=[("Metal", "18K yellow gold"), ("Stone", "Pear-cut diamond"), ("Chain", "18K, included"),
                ("Length", "Adjustable 16–18 in")]),
    dict(id="zohra", name="Zohra Jhumka Earrings", type="earrings", metals=["gold22"], occasion="festive",
         motif="earrings", badge="New", price="PKR 245,000", note="pair",
         desc="Granulated dome jhumkas finished with hand-strung pearls.",
         story="The domes are raised and then granulated — hundreds of tiny gold beads set one at a "
               "time — and finished with pearls strung on silk thread.",
         tags=["Handcrafted", "Pearl"],
         specs=[("Metal", "22K yellow gold"), ("Craft", "Granulation, hand-raised domes"),
                ("Drops", "Freshwater pearl"), ("Fitting", "Screw-back")]),
    dict(id="sana", name="Sana Engraved Bangles", type="bangles", metals=["gold22"], occasion="everyday",
         motif="bangles", price="PKR 720,000", note="set of four",
         desc="Set of four slim bangles with traditional hand engraving.",
         story="Four slim bangles, each engraved with the same repeating vine so the set reads as one "
               "piece when stacked and as four when worn alone.",
         tags=["Set of 4", "Hand Engraved"],
         specs=[("Metal", "22K yellow gold"), ("Set", "Four bangles"), ("Width", "5 mm each"),
                ("Finish", "Hand engraved, high polish")]),
    dict(id="noor", name="Noor Polki Bridal Set", type="bridal", metals=["gold22"], occasion="bridal",
         motif="bridal", badge="Signature", spotlight=True, price="Price on request", note="bespoke",
         desc="Uncut polki necklace with matching earrings and maang tikka.",
         story="Uncut polki set in kundan on a 22K base, with matching earrings and maang tikka. Each "
               "suite is drafted around your bridal palette and measured to the wearer, so no two are "
               "ever identical.",
         tags=["Bridal", "Polki", "Made to order"],
         specs=[("Metal", "22K gold, kundan-set"), ("Stones", "Uncut polki, pearls"),
                ("Craft", "Hand-set at the bench"), ("Delivery", "6–8 weeks, made to order")]),
    dict(id="roshni", name="Roshni Temple Necklace", type="necklace", metals=["gold22"], occasion="bridal",
         motif="necklace", price="PKR 1,240,000", note="approx. 48 g",
         desc="Temple-inspired nakshi work with ruby and emerald accents.",
         story="Nakshi work in the temple tradition, with ruby and emerald accents set into the "
               "repoussé panels. Made to order in the length you need.",
         tags=["Bridal", "22K Gold"],
         specs=[("Metal", "22K yellow gold"), ("Stones", "Ruby, emerald"), ("Weight", "Approx. 48 g"),
                ("Length", "Made to order")]),
    dict(id="hina", name="Hina Eternity Band", type="rings", metals=["rose", "white"], occasion="engagement",
         motif="rings", featured=True, price="PKR 210,000", note="per band",
         desc="Micro-set diamonds running continuously around the band.",
         story="Micro-set stones run the full circumference so the band reads the same from any angle. "
               "Comfort-fit inner profile for daily wear.",
         tags=["Ethical Diamonds", "Comfort Fit"],
         specs=[("Metal", "Rose or white gold"), ("Stones", "Micro-set diamonds"),
                ("Profile", "Comfort fit"), ("Sizing", "Made to size")]),
    dict(id="gulbahar", name="Gulbahar Emerald Choker", type="bridal", metals=["gold22"], occasion="bridal",
         motif="bridal", price="Price on request", note="bespoke",
         desc="Zambian emerald drops set in kundan on a 22K gold base.",
         story="Emerald drops in graduated sizes, each bezel cut to the stone rather than the stone "
               "cut to the bezel — which is why this one is always made to order.",
         tags=["Kundan", "Emerald"],
         specs=[("Metal", "22K gold"), ("Stones", "Zambian emerald"), ("Setting", "Kundan"),
                ("Delivery", "6–8 weeks")]),
    dict(id="mahtab", name="Mahtab Diamond Studs", type="earrings", metals=["white"], occasion="everyday",
         motif="pendants", badge="Bestseller", price="PKR 132,000", note="pair",
         desc="Four-prong princess studs that move from desk to dinner.",
         story="A pair that works with a shalwar kameez and with a shirt collar: four-prong princess "
               "studs with closed backs so they sit flat.",
         tags=["IGI Certified", "Everyday"],
         specs=[("Metal", "White gold"), ("Stones", "Princess-cut diamonds"),
                ("Setting", "Four-prong, closed back"), ("Fitting", "Push-back")]),
    dict(id="vasl", name="Vasl Couple Bands", type="rings", metals=["plat", "gold18"], occasion="engagement",
         motif="rings", price="PKR 298,000", note="pair",
         desc="Brushed platinum bands with a single hidden gold inlay.",
         story="A brushed platinum band with a single gold line set into the inner edge — visible to "
               "the wearer, not to the room. Engraving inside is included.",
         tags=["Platinum", "Engraving included"],
         specs=[("Metal", "Platinum, 18K inlay"), ("Finish", "Brushed"),
                ("Engraving", "Included"), ("Set", "Pair")]),
    dict(id="dilruba", name="Dilruba Halo Solitaire", type="rings", metals=["gold22"], occasion="engagement",
         motif="rings", badge="New", featured=True, price="PKR 465,000", note="incl. making",
         desc="A brilliant-cut solitaire ringed by a halo of smaller stones.",
         story="A round brilliant raised above the hand, ringed by a halo of smaller stones that "
               "doubles its apparent size. The band is forged from a single wire, so there is no "
               "seam to catch.",
         tags=["Halo", "22K Gold"],
         specs=[("Metal", "22K yellow gold"), ("Stones", "Brilliant centre with halo"),
                ("Setting", "Four-claw with halo"), ("Sizing", "Made to size")]),
    dict(id="zoya", name="Zoya Three-Stone Ring", type="rings", metals=["gold22"], occasion="engagement",
         motif="rings", featured=True, price="PKR 520,000", note="incl. making",
         desc="Past, present and future — three stones on a tapered band.",
         story="Three graduated stones on a band that tapers toward the fingertip: a centre "
               "brilliant flanked by two smaller rounds. The side stones are set first, so the "
               "centre always sits level.",
         tags=["Three-stone", "22K Gold"],
         specs=[("Metal", "22K yellow gold"), ("Stones", "Three brilliant-cut diamonds"),
                ("Centre", "0.75 ct"), ("Sizing", "Made to size")]),
    dict(id="reyaz", name="Reyaz Twisted Band", type="rings", metals=["rose"], occasion="everyday",
         motif="rings", featured=True, price="PKR 260,000", note="per band",
         desc="Two ribbons of rose gold twisted into one.",
         story="Two ribbons of gold twisted around each other, so the band reads differently in "
               "every light. Polished to a soft satin so it wears unmarked.",
         tags=["Twist", "Satin finish"],
         specs=[("Metal", "18K rose gold"), ("Width", "3 mm"),
                ("Finish", "Satin"), ("Profile", "Comfort fit")]),
    dict(id="mahnoor", name="Mahnoor Sapphire Ring", type="rings", metals=["gold22"], occasion="festive",
         motif="rings", badge="New", featured=True, price="PKR 425,000", note="incl. making",
         desc="A Ceylon sapphire crowned in a 22K gold filigree head.",
         story="A deep-blue Ceylon sapphire in a hand-drawn filigree head, openwork light enough to "
               "wear all evening. Blue and gold have been the house pairing since the first counter "
               "in the Liberty Market souk.",
         tags=["Ceylon Sapphire", "Filigree"],
         specs=[("Metal", "22K yellow gold"), ("Stone", "Ceylon sapphire"),
                ("Head", "Hand-drawn filigree"), ("Sizing", "Made to size")]),
    dict(id="areeba", name="Areeba Pearl Ring", type="rings", metals=["gold18"], occasion="gifting",
         motif="rings", price="PKR 185,000", note="incl. making",
         desc="A South Sea pearl cradled in an 18K gold collette.",
         story="A single South Sea pearl in a slim collette, close to the finger so it does not "
               "snag. The pearl is matched for lustre, not just size.",
         tags=["South Sea Pearl", "18K"],
         specs=[("Metal", "18K yellow gold"), ("Pearl", "South Sea, 8 mm"),
                ("Setting", "Collette"), ("Sizing", "Made to size")]),
    dict(id="dildar", name="Dildar Pavé Band", type="rings", metals=["white"], occasion="engagement",
         motif="rings", price="PKR 295,000", note="incl. making",
         desc="White gold pavé-set with hand-placed micro diamonds.",
         story="Micro diamonds placed by hand, stone by stone, around a slim white-gold band. The "
               "pavé is set low, so the band can be worn every day without the stones catching.",
         tags=["Pavé", "White Gold"],
         specs=[("Metal", "18K white gold"), ("Stones", "Hand-set micro diamonds"),
                ("Width", "2.4 mm"), ("Profile", "Comfort fit")]),
    dict(id="suhani", name="Suhani Signet Ring", type="rings", metals=["gold22"], occasion="everyday",
         motif="rings", price="PKR 150,000", note="incl. engraving",
         desc="A wide hand-engraved signet, made to your initials.",
         story="A wide face engraved to your initials or a date, under a hand-cut border. The "
               "inside is signed and dated, so the ring can be handed on.",
         tags=["Signet", "Hand Engraved"],
         specs=[("Metal", "22K yellow gold"), ("Width", "9 mm"),
                ("Engraving", "Initials or date"), ("Finish", "High polish")]),
    dict(id="zar", name="Zar Diamond Cluster Ring", type="rings", metals=["gold18"], occasion="festive",
         motif="rings", price="PKR 340,000", note="incl. making",
         desc="A cluster of mixed-cut diamonds on an 18K gold base.",
         story="Rounds, pears and brilliants clustered so light passes through the whole head at "
               "once. It reads larger than its weight — which is the point.",
         tags=["Cluster", "18K"],
         specs=[("Metal", "18K yellow gold"), ("Stones", "Mixed-cut diamond cluster"),
                ("Setting", "Cluster"), ("Sizing", "Made to size")]),
    dict(id="sitara", name="Sitara Filigree Kada", type="bangles", metals=["gold22"], occasion="festive",
         motif="bangles", price="PKR 545,000", note="approx. 32 g",
         desc="Wide kada built from hand-drawn gold filigree scrolls.",
         story="Filigree drawn by hand into scrollwork, then assembled over a frame so the whole kada "
               "weighs far less than it looks.",
         tags=["Filigree", "22K Gold"],
         specs=[("Metal", "22K yellow gold"), ("Weight", "Approx. 32 g"),
                ("Width", "22 mm"), ("Finish", "Hand drawn filigree")]),
    dict(id="sahr", name="Sahr Gold Coin Pendant", type="necklace", metals=["gold22"], occasion="investment",
         motif="pendants", price="PKR 96,000", note="incl. coin",
         desc="Hallmarked 22K bullion coin framed in a rope-edge bezel.",
         story="A bullion coin in a rope-edge bezel, so it can be worn or returned to the vault. "
               "Coins are sold with their assay papers.",
         tags=["Bullion", "24K Coin"],
         specs=[("Bezel", "22K gold"), ("Coin", "24K bullion, hallmarked"),
                ("Papers", "Included"), ("Chain", "Optional")]),
    dict(id="nazm", name="Nazm Pearl Drop Earrings", type="earrings", metals=["gold18"], occasion="gifting",
         motif="earrings", price="PKR 88,000", note="pair",
         desc="South Sea pearl drops swinging from hammered gold hoops.",
         story="Hoops hammered to a soft irregular surface, with South Sea pearls hung so they catch "
               "the light when the wearer turns.",
         tags=["South Sea Pearl", "18K"],
         specs=[("Metal", "18K yellow gold"), ("Pearls", "South Sea drops"),
                ("Finish", "Hand hammered"), ("Fitting", "Hook")]),
    dict(id="maahru", name="Maahru Diamond Bangle", type="bangles", metals=["white", "gold18"], occasion="bridal",
         motif="bangles", price="PKR 465,000", note="single",
         desc="A formal bangle of channel-set diamonds with gold edging.",
         story="A single formal bangle: channel-set stones with a gold edge that frames the line and "
               "protects the setting in daily wear.",
         tags=["IGI Certified", "Formal"],
         specs=[("Metal", "White gold, 18K edge"), ("Stones", "Channel-set diamonds"),
                ("Width", "8 mm"), ("Sizing", "Made to size")]),
]

TESTIMONIALS = [
    dict(name="Ayesha Rehman", role="Bridal client, Lahore", rating=5,
         text="They designed my entire bridal set from a sketch I brought in. The polki work was finer "
              "than anything I saw in the market — and the price was settled before a single gram was melted."),
    dict(name="Bilal Ahmed", role="Investment buyer", rating=5,
         text="I have bought bullion here for nine years. Transparent weighing, proper hallmarking, "
              "documented invoicing. That consistency is why my family keeps coming back."),
    dict(name="Sana Tariq", role="Engagement purchase", rating=5,
         text="I was nervous about choosing a solitaire. Their consultant spent two hours with me under "
              "the loupe, showed me the certificate, and never once pushed me upwards."),
    dict(name="Hina & Faisal", role="Wedding bands, 2025", rating=5,
         text="Both our bands were hand-engraved with our wedding date. The detailing is so clean it "
              "reads as machine work — except no machine could do this."),
    dict(name="Zeeshan Malik", role="Restoration", rating=4,
         text="My mother\u2019s old necklace had a broken clasp and worn links. They restored it matching "
              "the original karigar work. You cannot tell where the repair begins."),
    dict(name="Farah Naz", role="Repeat client", rating=5,
         text="The lifetime exchange promise is real. I upgraded an old chain last month and got a fair, "
              "clearly explained rate on the spot. No drama, no haggling."),
]

NAV_ITEMS = [
    ("index.html", "Home", "home"),
    ("about.html", "About", "about"),
    ("collections.html", "Collections", "collections"),
    ("atelier.html", "Atelier", "atelier"),
    ("visit.html", "Visit", "visit"),
]


def esc(text):
    return html.escape(text, quote=True)


def product_by_id(pid):
    return next(p for p in PRODUCTS if p["id"] == pid)


def related_to(p, limit=3):
    """Same occasion or type first, then anything else — never the piece itself."""
    others = [o for o in PRODUCTS if o["id"] != p["id"]]
    scored = sorted(others, key=lambda o: (
        0 if o["occasion"] == p["occasion"] else 1,
        0 if o["type"] == p["type"] else 1,
    ))
    return scored[:limit]


# ---------------------------------------------------------------------------
# 3b. PRODUCT PHOTOGRAPHS
# Drop a photograph in assets/products/ named after the piece's id
# (assets/products/meher.jpg) and the next build uses it in the card, the
# quick view and the piece page. Without a photo the line-drawing motif is
# used instead, so the site never shows a broken image.
# ---------------------------------------------------------------------------
PRODUCT_PHOTO_EXTS = (".jpg", ".jpeg", ".png", ".webp", ".avif")


def product_photo(p):
    """Web path to the piece's photograph, or None when none has been added."""
    for ext in PRODUCT_PHOTO_EXTS:
        name = "products/%s%s" % (p["id"], ext)
        if os.path.exists(os.path.join(HERE, "assets", name)):
            return "assets/" + name
    return None


def product_media(p):
    """The piece's visual: its photograph when one exists, else the motif."""
    src = product_photo(p)
    if src:
        return ('<img class="product-photo" src="%s" alt="%s" '
                'loading="lazy" decoding="async">' % (src, esc(p["name"])))
    return MOTIF[p["motif"]]


def spotlight_product():
    """The single featured piece: the spotlight flag, then featured, then first."""
    return (next((p for p in PRODUCTS if p.get("spotlight")), None)
            or next((p for p in PRODUCTS if p.get("featured")), None)
            or PRODUCTS[0])


def featured_products():
    return [p for p in PRODUCTS if p.get("featured")]


def ring_count():
    return sum(1 for p in PRODUCTS if p["type"] == "rings")


def catalogue_json_block():
    """Everything the quick view needs, as one JSON island on every page.
    The script reads it by id, so opening details never fetches anything."""
    items = []
    for p in PRODUCTS:
        items.append({
            "id": p["id"], "name": p["name"], "type": p["type"],
            "occasion": p["occasion"], "metals": [METALS[m] for m in p["metals"]],
            "badge": p.get("badge", ""), "price": p["price"], "note": p["note"],
            "desc": p["desc"], "story": p["story"], "tags": p["tags"],
            "specs": [[k, v] for k, v in p["specs"]],
            "motif": p["motif"], "photo": product_photo(p),
            "href": "piece-%s.html" % p["id"],
        })
    payload = {"motifs": MOTIF, "types": TYPES, "occasions": OCCASIONS, "items": items}
    return ('<script type="application/json" id="catalogue-data">%s</script>'
            % json.dumps(payload, ensure_ascii=False, separators=(",", ":")))


# ---------------------------------------------------------------------------
# 4. SHARED CHROME
# ---------------------------------------------------------------------------
NOSCRIPT = """<noscript>
  <style>
    /* Without JS the intro could never retire — show the hero instead. */
    .intro { display: none !important; }
    .intro-wrap .hero-intro > *,
    .intro-wrap .hero-showcase,
    .intro-wrap .scroll-indicator { opacity: 1 !important; transform: none !important; }
    [data-aos] { opacity: 1 !important; transform: none !important; }
  </style>
</noscript>"""

INTRO = """<div class="intro" id="intro" aria-hidden="true"
     style="position:fixed;inset:0;z-index:2000;display:grid;place-items:center;background:#000">
  <span class="intro-inner">
    <span class="intro-mark">ALM</span>
    <span class="intro-rule"></span>
    <span class="intro-word">Jewellers</span>
  </span>
</div>"""

SVG_DEFS = """<svg width="0" height="0" style="position:absolute;overflow:hidden" aria-hidden="true" focusable="false">
  <defs>
    <linearGradient id="goldFill" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#CBAA6E"/><stop offset="55%" stop-color="#B08C4A"/>
      <stop offset="100%" stop-color="#96773C"/>
    </linearGradient>
    <linearGradient id="goldStroke" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#A9853F"/><stop offset="55%" stop-color="#B08C4A"/>
      <stop offset="100%" stop-color="#8A6A2B"/>
    </linearGradient>
    <linearGradient id="goldFillDark" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#E8D3A6"/><stop offset="55%" stop-color="#D2B478"/>
      <stop offset="100%" stop-color="#B08C4A"/>
    </linearGradient>
    <linearGradient id="goldStrokeDark" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#D2B478"/><stop offset="50%" stop-color="#E8D3A6"/>
      <stop offset="100%" stop-color="#B08C4A"/>
    </linearGradient>
  </defs>
</svg>"""


def favicon_links():
    """Browser-tab icon: your mark when you have one, the diamond if not."""
    icon = find_logo_file(LOGO_ICON_NAMES) or LOGO_FILE
    if not icon:
        return ("<link rel=\"icon\" href=\"data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg'"
                " viewBox='0 0 32 32'><rect width='32' height='32' rx='7' fill='%231D1D1F'/>"
                "<path d='M16 6l7 10-7 10-7-10z' fill='%23B08C4A'/></svg>\">")
    typ = mime_of(icon)
    type_attr = ' type="%s"' % typ if typ else ""
    links = '<link rel="icon" href="%s"%s>' % (icon, type_attr)
    if typ != "image/svg+xml":
        # iOS ignores SVG for the home-screen icon, so give it the raster file.
        links += '\n<link rel="apple-touch-icon" href="%s">' % icon
    return links


def head(title, desc):
    return f"""<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="theme-color" content="#ffffff">
<title>{esc(title)}</title>
<meta name="description" content="{esc(desc)}">
<meta property="og:title" content="{esc(title)}">
<meta property="og:description" content="{esc(desc)}">
<meta property="og:type" content="website">
<link rel="stylesheet" href="styles.css">
{favicon_links()}
{NOSCRIPT}
</head>"""


def logo(href="index.html"):
    """The house logo: your file when there is one, the ALM monogram if not.

    The link carries the accessible name, so the artwork itself is decorative
    (empty alt) and a screen reader announces the business name, not a filename.
    """
    label = esc(SITE["name"]) + " — home"

    if LOGO_FILE and LOGO_MODE == "lockup":
        # The artwork already contains the name, so no wordmark text beside it.
        return f"""<a href="{href}" class="logo logo--lockup" aria-label="{label}">
        <img class="logo-img" src="{LOGO_FILE}" alt="" decoding="async">
      </a>"""

    if LOGO_FILE:
        # Symbol only: it stands in for the ALM square, the name stays as text.
        return f"""<a href="{href}" class="logo logo--mark" aria-label="{label}">
        <img class="logo-img logo-img--mark" src="{LOGO_FILE}" alt="" decoding="async">
        <span class="logo-words">
          <span class="logo-text">{esc(SITE['short'])}</span>
          <span class="logo-sub">Jewellers</span>
        </span>
      </a>"""

    return f"""<a href="{href}" class="logo" aria-label="{label}">
        <span class="logo-mark" aria-hidden="true"><span>ALM</span></span>
        <span class="logo-words">
          <span class="logo-text">{esc(SITE['short'])}</span>
          <span class="logo-sub">Jewellers</span>
        </span>
      </a>"""


def nav(active):
    links = ""
    for href, label, key in NAV_ITEMS:
        cur = ' aria-current="page"' if key == active else ""
        cls = "nav-link active" if key == active else "nav-link"
        links += f'\n        <a href="{href}" class="{cls}"{cur}>{label}</a>'
    cta = ' aria-current="page"' if active == "appointment" else ""
    return f"""<div class="progress" id="progress" aria-hidden="true"></div>

<nav class="navbar" id="navbar" aria-label="Primary">
  <div class="container nav-container">
    {logo()}
    <div class="nav-links" id="navLinks">{links}
        <a href="appointment.html" class="btn btn-primary nav-cta"{cta}>Book</a>
    </div>
    <button class="mobile-menu-btn" id="mobileMenuBtn" aria-label="Toggle navigation menu"
            aria-expanded="false" aria-controls="navLinks"><span class="hamburger"></span></button>
  </div>
</nav>"""


def footer():
    return f"""<footer class="footer">
  <div class="container">
    <div class="footer-grid">
      <div class="footer-brand">
        {logo()}
        <p class="footer-tagline">{esc(TAGLINE)}</p>
        <div class="social-links">
          <a class="social-link" href="{SITE['instagram']}" target="_blank" rel="noopener" aria-label="Instagram">{ICON['instagram']}</a>
          <a class="social-link" href="{SITE['facebook']}" target="_blank" rel="noopener" aria-label="Facebook">{ICON['facebook']}</a>
          <a class="social-link" href="{wa_general()}" target="_blank" rel="noopener" aria-label="WhatsApp">{ICON['wa']}</a>
          <a class="social-link" href="{SITE['youtube']}" target="_blank" rel="noopener" aria-label="YouTube">{ICON['youtube']}</a>
        </div>
      </div>

      <div class="footer-links">
        <h3>Explore</h3>
        <ul>
          <li><a href="about.html">About</a></li>
          <li><a href="collections.html">Collections</a></li>
          <li><a href="atelier.html">The atelier</a></li>
          <li><a href="clients.html">Client stories</a></li>
          <li><a href="visit.html">Visit us</a></li>
        </ul>
      </div>

      <div class="footer-links">
        <h3>Services</h3>
        <ul>
          <li><a href="appointment.html">Bridal consultation</a></li>
          <li><a href="appointment.html">Bespoke commissions</a></li>
          <li><a href="appointment.html">Old gold exchange</a></li>
          <li><a href="appointment.html">Repair &amp; polishing</a></li>
          <li><a href="appointment.html">Valuation &amp; certification</a></li>
        </ul>
      </div>

      <div class="footer-contact">
        <h3>Showroom</h3>
        <address>
          <p>{ICON['pin']}<span>{esc(SITE['address_1'])}<br>{esc(SITE['address_2'])}</span></p>
          <p>{ICON['phone']}<a href="tel:{SITE['phone_display'].replace(' ', '')}">{esc(SITE['phone_display'])}</a></p>
          <p>{ICON['mail']}<a href="mailto:{SITE['email']}">{esc(SITE['email'])}</a></p>
        </address>
        <div class="hours">
          <p><strong>Hours</strong></p>
          <p>{esc(SITE['hours_week'])}</p>
          <p>{esc(SITE['hours_sun'])}</p>
        </div>
      </div>
    </div>

    <div class="newsletter">
      <div>
        <h3>First look at new arrivals</h3>
        <p>Bridal previews and new pieces, twice a month. No noise.</p>
      </div>
      <form class="newsletter-form" id="newsletterForm" novalidate>
        <label class="visually-hidden" for="newsletterEmail">Email address</label>
        <input type="email" id="newsletterEmail" placeholder="Your email address" autocomplete="email" required>
        <button type="submit" class="btn btn-primary">Subscribe</button>
      </form>
      <p class="newsletter-msg" id="newsletterMsg" role="status" aria-live="polite"></p>
    </div>

    <div class="footer-bottom">
      <p>&copy; <span id="year">2026</span> {esc(SITE['name'])}. All rights reserved.</p>
      <div class="footer-legal">
        <a href="privacy.html">Privacy Policy</a>
        <a href="terms.html">Terms of Sale</a>
        <a href="visit.html">Contact</a>
      </div>
    </div>
  </div>
</footer>

<a class="whatsapp-float" href="{wa_general()}" target="_blank" rel="noopener"
   aria-label="Chat with us on WhatsApp">{ICON['wa']}</a>

<button class="back-to-top" id="backToTop" aria-label="Back to top" aria-hidden="true">{ICON['down']}</button>"""


def page(title, desc, active, content, intro=False, head_extra=""):
    return f"""<!DOCTYPE html>
{BUILD_NOTE}
<html lang="en">
{head(title, desc)}
<body>
<a class="skip-link" href="#main">Skip to content</a>
{f'{INTRO}' if intro else ''}
{nav(active)}
{content}
{footer()}
{SVG_DEFS}
{head_extra}
{catalogue_json_block()}
<script src="script.js"></script>
</body>
</html>
"""


def page_head(crumb, title, lede, dark=False):
    band = " page-head--dark" if dark else ""
    return f"""<header class="page-head{band}">
  <div class="container">
    <nav class="crumb" aria-label="Breadcrumb"><a href="index.html">Home</a><span aria-hidden="true">/</span><span>{esc(crumb)}</span></nav>
    <h1>{title}</h1>
    <p class="page-lede">{lede}</p>
  </div>
</header>"""


def cta_band(title, text, primary_href="appointment.html", primary_label="Book an appointment",
             second_href=None, second_label=None):
    second = ""
    if second_href:
        second = f'\n      <a class="btn btn-link" href="{second_href}">{second_label}{ICON["chev"]}</a>'
    return f"""<section class="section--dark band-cta">
  <div class="container band-cta-inner" data-aos="fade-up">
    <h2>{title}</h2>
    <p>{text}</p>
    <div class="band-cta-actions">
      <a class="btn btn-light" href="{primary_href}">{primary_label}</a>{second}
    </div>
  </div>
</section>"""


def card(p, delay=0, hidden=False):
    metals = " · ".join(METALS[m] for m in p["metals"])
    badge = ""
    if p.get("badge"):
        cls = "badge gold" if p["badge"] in ("Bestseller", "Signature") else "badge"
        badge = f'\n          <span class="{cls}">{esc(p["badge"])}</span>'
    tags = "".join(f'\n              <span class="tag">{esc(t)}</span>' for t in p["tags"])
    hidden_attr = " hidden" if hidden else ""
    return f"""<article class="product-card"{hidden_attr} data-type="{p['type']}" data-occasion="{p['occasion']}"
                 data-metals="{' '.join(p['metals'])}" style="animation-delay:{delay}ms">
            <div class="product-media">{badge}
              <a class="media-link" href="piece-{p['id']}.html" tabindex="-1" aria-hidden="true">{product_media(p)}</a>
              <button class="quickview-btn" type="button" data-quickview="{p['id']}"
                      aria-label="View all details for {esc(p['name'])}">View details</button>
              <button class="fav-btn" type="button" aria-label="Save {esc(p['name'])} to wishlist"
                      aria-pressed="false" data-fav="{p['id']}">{ICON['heart']}</button>
            </div>
            <div class="product-body">
              <span class="product-cat">{TYPES[p['type']]} · {OCCASIONS[p['occasion']]}</span>
              <h3 class="product-name"><a href="piece-{p['id']}.html">{esc(p['name'])}</a></h3>
              <p class="product-desc">{esc(p['desc'])}</p>
              <div class="product-meta">{tags}
                <span class="tag">{esc(metals)}</span>
              </div>
              <div class="product-foot">
                <span class="price">{esc(p['price'])}<small>{esc(p['note'])}</small></span>
                <button class="enquire-btn" type="button"
                        data-enquire="{esc(p['name'])}|{esc(p['price'])}|piece-{p['id']}.html">
                  Enquire {ICON['arrow']}
                </button>
              </div>
            </div>
          </article>"""


def spotlight(p):
    specs = "".join(
        f'\n              <div class="spec"><dt>{esc(k)}</dt><dd>{esc(v)}</dd></div>'
        for k, v in p["specs"])
    return f"""<article class="spotlight" data-type="{p['type']}" data-occasion="{p['occasion']}"
                 data-metals="{' '.join(p['metals'])}" id="spotlight" data-aos="fade-up">
            <div class="spotlight-media">{product_media(p)}</div>
            <div class="spotlight-body">
              <span class="spotlight-eyebrow">{ICON['gem']} Featured piece</span>
              <h2 class="spotlight-name"><a href="piece-{p['id']}.html">{esc(p['name'])}</a></h2>
              <p class="spotlight-desc">{esc(p['story'])}</p>
              <dl class="spotlight-specs">{specs}</dl>
              <div class="spotlight-foot">
                <span class="spotlight-price">{esc(p['price'])}<small>{esc(p['note'])}</small></span>
                <a class="btn btn-primary" href="piece-{p['id']}.html">View the piece</a>
                <a class="btn btn-secondary" href="appointment.html">Book a viewing</a>
              </div>
            </div>
          </article>"""


def star_row(n):
    return ('<div class="stars" role="img" aria-label="%d out of 5 stars">%s</div>'
            % (n, ICON["star"] * n + ICON["starline"] * (5 - n)))


def testimonial(t, i=0):
    initials = "".join(w[0] for w in t["name"].split()[:2]).upper()
    return f"""<figure class="testimonial" data-aos="fade-up" data-aos-delay="{i * 70}">
          {star_row(t['rating'])}
          <blockquote>{esc(t['text'])}</blockquote>
          <figcaption class="testimonial-author">
            <span class="author-avatar" aria-hidden="true">{initials}</span>
            <span>
              <span class="author-name">{esc(t['name'])}</span>
              <span class="author-role">{esc(t['role'])}</span>
            </span>
          </figcaption>
        </figure>"""


# ---------------------------------------------------------------------------
# 5. PAGES
# ---------------------------------------------------------------------------
def page_home():
    feat = spotlight_product()
    hero_img = find_hero_image()
    if hero_img:
        hero_open = '<section class="hero hero--dark intro-wrap hero--photo" id="home">'
        hero_preload = '<link rel="preload" as="image" href="%s">' % hero_img
        # A real element rather than a CSS background: it can be cover-fitted on
        # wide screens and become a band beneath the copy on a phone, where a
        # background would put the jewellery right behind the headline.
        # Decorative, so alt is empty and the wrapper is hidden from AT.
        hero_media = (
            '\n  <div class="hero-photo" aria-hidden="true">'
            '\n    <img src="%s" alt="" decoding="async" fetchpriority="high">'
            '\n  </div>' % hero_img
        )
    else:
        hero_open = '<section class="hero hero--dark intro-wrap" id="home">'
        hero_preload = ""
        hero_media = ""
    tiles = [
        ("collections.html", "Collections", "Rings, necklaces, earrings, bangles and full bridal sets — "
                                           "filter the catalogue by type, metal or occasion."),
        ("atelier.html", "The atelier", "How a commission is made, from the first sketch to the final "
                                        "polish — four unhurried stages."),
        ("visit.html", "Visit us", "The showroom in Gulberg III: hours, directions, and what to bring "
                                   "if you are exchanging old gold."),
    ]
    tile_html = "".join(f"""
        <a class="tile" href="{href}" data-aos="fade-up" data-aos-delay="{i * 70}">
          <h3>{title}</h3>
          <p>{text}</p>
          <span class="tile-link">Learn more {ICON['chev']}</span>
        </a>""" for i, (href, title, text) in enumerate(tiles))

    feat_cards = "".join(card(p, i * 45) + "\n        " for i, p in enumerate(featured_products()))

    content = f"""<main id="main">
<!-- ============================ HERO ============================ -->
{hero_open}
  <div class="container">
    <div class="hero-intro">
      <span class="hero-badge">Est. 1979 &middot; Lahore</span>
      <h1>Heirlooms in <span class="gold-shine">gold</span>.</h1>
      <p class="hero-tagline">Made to last generations.</p>
      <p class="hero-description">
        Bridal sets, certified solitaires and bespoke commissions — hand-finished
        at our bench in Gulberg.
      </p>
      <div class="hero-actions">
        <a href="collections.html" class="btn btn-light">Explore the collections</a>
        <a href="appointment.html" class="btn btn-link">Book a private viewing {ICON['chev']}</a>
      </div>
    </div>

    <div class="hero-showcase" aria-hidden="true">
      <div class="showcase-stage">
        <span class="spark showcase-spark-1"></span>
        <span class="spark showcase-spark-2"></span>
        <span class="spark showcase-spark-3"></span>
        {motif_dark('bridal')}
      </div>
    </div>

    <div class="scroll-indicator" aria-hidden="true">{ICON['down']}</div>
  </div>{hero_media}
</section>

<!-- ============================ FEATURED ============================ -->
<section class="section">
  <div class="container">
    <div class="section-header">
      <span class="section-tag">This season</span>
      <h2>The piece we are making most.</h2>
    </div>
    {spotlight(feat)}
  </div>
</section>

<!-- ============================ FEATURED RINGS ============================ -->
<section class="section" id="featured">
  <div class="container">
    <div class="section-header">
      <span class="section-tag">Featured this month</span>
      <h2>The rings clients ask for by name.</h2>
    </div>
    <div class="products-grid" role="list" aria-label="Featured rings">
        {feat_cards}
    </div>
    <p class="section-more">
      <a href="collections.html?type=rings">Browse all {ring_count()} rings {ICON['arrow']}</a>
    </p>
  </div>
</section>

<!-- ============================ EXPLORE TILES ============================ -->
<section class="section section--alt">
  <div class="container">
    <div class="section-header">
      <span class="section-tag">Where to go next</span>
      <h2>Everything, in three minutes.</h2>
    </div>
    <div class="tiles">{tile_html}
    </div>
  </div>
</section>

{cta_band("Come and see it in daylight.",
          "Gold looks different under our light than under anyone else's. Bring your family — there is tea.",
          "appointment.html", "Book an appointment", "visit.html", "Get directions")}
</main>
"""
    note = "" if hero_img else (
        "<!-- No hero image found. Add your photograph as assets/hero.jpg "
        "(or .png/.webp/.avif) and rebuild to use it as the hero background. -->")
    return page(f"{SITE['short']} — Fine jewellery in Lahore",
                TAGLINE + " Book a private showroom consultation.", "home", content,
                intro=True, head_extra=(hero_preload + note))


def page_about():
    content = f"""<main id="main">
{page_head("About", "A jewellery house in Gulberg.",
           "We make gold, diamond and polki jewellery to order, and we look after it "
           "long after it leaves the counter.")}

<section class="section">
  <div class="container split">
    <div class="prose" data-aos="fade-right">
      <p class="lede">Alif Laam Meem Jewellers began at a single counter in the Liberty Market gold souk.
      Today it is a family workshop and showroom, and the work is still done the same way: at the bench,
      by hand, in front of the person buying it.</p>

      <p>Most of what we sell is made rather than bought in. A bride brings a sketch or a photograph;
      our karigars draw it properly, we quote it in writing, and then the piece is built —
      raised, engraved, set and polished in stages you are welcome to watch.</p>

      <p>We keep the paperwork as carefully as the jewellery. Every piece is weighed in front of you,
      hallmarked, and handed over with a bill that lists the metal, the stones and the making charge
      separately, so you always know what you paid for which part.</p>

      <p>And because jewellery is worn rather than stored, the relationship does not end at the sale.
      Bring a piece back in a year or in twenty; we will clean it, re-polish it, re-size it, or tell you
      honestly what it is worth.</p>
    </div>

    <div class="panel" data-aos="fade-left" aria-hidden="true">
      {motif_dark('necklace')}
    </div>
  </div>
</section>

<section class="section section--alt">
  <div class="container">
    <div class="section-header">
      <span class="section-tag">How we work</span>
      <h2>Three habits we do not break.</h2>
    </div>
    <div class="process-grid">
      <article class="step" data-aos="fade-up">
        <span class="step-num">Weighed</span>
        <h3>In front of you</h3>
        <p>The scale sits on the counter. Metal, stones and making charges are listed separately on the bill.</p>
      </article>
      <article class="step" data-aos="fade-up" data-aos-delay="70">
        <span class="step-num">Made</span>
        <h3>Rather than bought in</h3>
        <p>Ordered pieces are built in our own workshop, so we can change a length, a clasp or a stone size.</p>
      </article>
      <article class="step" data-aos="fade-up" data-aos-delay="140">
        <span class="step-num">Kept</span>
        <h3>For as long as you own it</h3>
        <p>Cleaning, polishing, re-sizing and honest valuation advice, for pieces bought here or elsewhere.</p>
      </article>
    </div>
  </div>
</section>

{cta_band("Sit with a jeweller, not a salesperson.",
          "Bring a sketch, a photograph, or just an idea. We will tell you what it takes to make it.",
          "appointment.html", "Book a consultation", "collections.html", "See the collections")}
</main>
"""
    return page(f"About — {SITE['name']}",
                "A family jewellery workshop and showroom in Gulberg, Lahore: gold, diamond and polki "
                "pieces made to order, with the weight and the paperwork shown in front of you.",
                "about", content)


def page_collections():
    feat = spotlight_product()
    others = [p for p in PRODUCTS if p["id"] != feat["id"]]
    # Progressive reveal: only the first batch ships visible; the rest stay
    # hidden until script.js reveals them as the visitor scrolls. The noscript
    # override below makes every card visible when JS is off.
    cards = "".join(card(p, i * 45, hidden=(i >= REVEAL_BATCH)) + "\n          "
                    for i, p in enumerate(others))
    content = f"""<main id="main">
{page_head("Collections", "Find the piece that finds you.",
           "Filter the catalogue by type, metal or occasion. Prices are indicative and follow the "
           "gold rate on the day you buy.")}

<section class="section">
  <div class="container">
    <div class="filter-tabs-wrap">
      <div class="filter-tabs" role="group" aria-label="Filter collections by">
        <button class="filter-tab active" type="button" aria-pressed="true" data-filter="all">All pieces</button>
        <button class="filter-tab" type="button" aria-pressed="false" data-filter="type">By type</button>
        <button class="filter-tab" type="button" aria-pressed="false" data-filter="metal">By metal</button>
        <button class="filter-tab" type="button" aria-pressed="false" data-filter="occasion">By occasion</button>
      </div>
    </div>

    <div class="sub-filters" id="subFilters" role="group" aria-label="Refine selection" aria-live="polite"></div>

    {spotlight(feat)}

    <div class="products-grid" id="productsGrid" role="list" aria-label="Jewellery catalogue">
          {cards}
    </div>

    <p class="visually-hidden" id="filterStatus" role="status" aria-live="polite"></p>

    <p class="collections-note" id="noResults" hidden>
      Nothing in this selection yet — call us and we will make it for you.
    </p>

    <!-- More of the catalogue reveals itself as you scroll; the button is the
         no-scroll fallback and the explicit "load more" for everyone. -->
    <div class="reveal-foot" id="revealFoot">
      <p class="reveal-status" id="revealStatus" role="status" aria-live="polite"></p>
      <button class="btn btn-secondary" type="button" id="revealMore">Show more pieces</button>
    </div>

    <div class="collections-foot">
      <p class="collections-note">
        Looking for something that is not listed? We make pieces from a photograph, a sketch, or an
        heirloom to be reimagined.
      </p>
      <a href="appointment.html" class="btn btn-secondary">Book a private viewing</a>
    </div>
  </div>
</section>

{cta_band("Not sure which one?", "Send us a message and we will pull a tray before you arrive.",
          "appointment.html", "Book an appointment", wa_general(), "Ask on WhatsApp")}
</main>
"""
    # Without JS the grid cannot progressively reveal itself — show the whole
    # catalogue instead of the first batch.
    noscript_grid = (
        "<noscript><style>#productsGrid .product-card{display:flex !important}</style></noscript>"
    )
    return page(f"Collections — {SITE['name']}",
                "Browse rings, necklaces, earrings, bangles and bridal sets. Filter by type, metal or "
                "occasion; every piece has its own page with specs and pricing.",
                "collections", content, head_extra=noscript_grid)


def page_atelier():
    steps = [
        ("01", "Consultation", "Sit with a jeweller, not a salesperson. We discuss the occasion, your budget, "
                               "the metal and the stone — and whether the idea in your head is the right one.", "chat"),
        ("02", "Sketch &amp; quote", "Hand drawings of the piece, and a written estimate that itemises metal, "
                                     "stones and making. Nothing is fixed until you approve the quote.", "sketch"),
        ("03", "Hand crafting", "Our karigars raise, engrave, set and polish the piece in stages. You are welcome "
                                "at the bench for any of them, and we send photographs as it progresses.", "bench"),
        ("04", "Assay &amp; handover", "Independent hallmarking and certification where needed, a final weigh-in, "
                                       "and the piece handed over with its paperwork and a service file.", "shield"),
    ]
    step_html = "".join(f"""
      <article class="step" data-aos="fade-up" data-aos-delay="{i * 60}">
        <span class="step-num">{num}</span>
        <h2>{title}</h2>
        <p>{text}</p>
        <span class="step-icon" aria-hidden="true">{ICON[icon]}</span>
      </article>""" for i, (num, title, text, icon) in enumerate(steps))

    content = f"""<main id="main">
{page_head("Atelier", "How a commission is made.",
           "Four stages, and you are part of all of them. Most commissions take three to eight weeks "
           "depending on the stone and the setting.")}

<section class="section">
  <div class="container">
    <div class="process-grid">{step_html}
    </div>
  </div>
</section>

<section class="section section--alt">
  <div class="container split">
    <div class="prose" data-aos="fade-right">
      <h2>What to bring</h2>
      <p class="lede">A commission goes faster when you bring anything you already love.</p>
      <ul class="checks">
        <li>{ICON['check']}A sketch, a photograph, or a screenshot — anything that shows the shape you mean.</li>
        <li>{ICON['check']}A piece you already own that fits the way you want, for sizing and weight.</li>
        <li>{ICON['check']}Old gold you would like remade, exchanged or valued. Bring the paperwork if you have it.</li>
        <li>{ICON['check']}Your dates. If it is for a wedding, tell us the wedding date first, not last.</li>
      </ul>
    </div>
    <div class="panel" data-aos="fade-left" aria-hidden="true">{motif_dark('rings')}</div>
  </div>
</section>

{cta_band("Start with a conversation.",
          "No deposit, no obligation, and no pressure to decide on the day.",
          "appointment.html", "Book a consultation", "collections.html", "See finished pieces")}
</main>
"""
    return page(f"The atelier — {SITE['name']}",
                "How a bespoke piece is made: consultation, sketch and quote, hand crafting, then assay "
                "and handover. What to bring to your first appointment.",
                "atelier", content)


def page_appointment():
    content = f"""<main id="main">
{page_head("Appointment", "Book a private viewing.",
           "Tell us what you are looking for and we will prepare a tray before you arrive. "
           "We confirm every appointment on WhatsApp within two hours.")}

<section class="section">
  <div class="container appointment-wrapper">
    <div class="appointment-info" data-aos="fade-right">
      <h2>A quiet room, a tray of golds, and all the time you need.</h2>
      <p>Whether you are choosing an engagement solitaire, commissioning a bridal suite, or bringing in
      old gold to exchange, your consultant will have the pieces ready when you walk in.</p>

      <div class="appointment-benefits">
        <span class="benefit"><i class="benefit-icon">✓</i> Private viewing room</span>
        <span class="benefit"><i class="benefit-icon">✓</i> Loupe &amp; certificate review</span>
        <span class="benefit"><i class="benefit-icon">✓</i> No obligation to buy</span>
        <span class="benefit"><i class="benefit-icon">✓</i> Free old-gold valuation</span>
        <span class="benefit"><i class="benefit-icon">✓</i> Refreshments served</span>
        <span class="benefit"><i class="benefit-icon">✓</i> Discreet side entrance</span>
      </div>

      <div class="contact-quick">
        <h3>Prefer to speak first?</h3>
        <div class="quick-contacts">
          <a class="quick-contact" href="{wa('Assalam-o-Alaikum. I would like to book a showroom consultation at ' + SITE['name'] + '.')}" target="_blank" rel="noopener">
            <span class="contact-icon" aria-hidden="true">{ICON['wa']}</span>
            <span>
              <span class="contact-label">WhatsApp</span>
              <span class="contact-value">{esc(SITE['phone_display'])}</span>
            </span>
          </a>
          <a class="quick-contact" href="tel:{SITE['phone_display'].replace(' ', '')}">
            <span class="contact-icon" aria-hidden="true">{ICON['phone']}</span>
            <span>
              <span class="contact-label">Call the showroom</span>
              <span class="contact-value">{esc(SITE['phone_display'])}</span>
            </span>
          </a>
        </div>
      </div>
    </div>

    <div class="appointment-form-wrapper" data-aos="fade-left">
      <h2 class="form-heading">Request your appointment</h2>
      <p class="form-subheading">Fill this in and we will confirm your slot on WhatsApp within two hours.</p>

      <form class="appointment-form" id="appointmentForm" data-wa-number="{SITE['whatsapp']}"
            data-wa-name="{esc(SITE['name'])}" novalidate>
        <input type="hidden" name="text" id="whatsappMessage" value="">

        <div class="form-row">
          <div class="form-group">
            <label for="name">Full name <span class="req">*</span></label>
            <input type="text" id="name" name="name" autocomplete="name" placeholder="e.g. Ayesha Rehman" required>
            <span class="error-msg">Please enter your full name.</span>
          </div>
          <div class="form-group">
            <label for="phone">Phone / WhatsApp <span class="req">*</span></label>
            <input type="tel" id="phone" name="phone" autocomplete="tel" placeholder="+92 3XX XXX XXXX" required>
            <span class="error-msg">Enter a reachable phone number.</span>
          </div>
        </div>

        <div class="form-row">
          <div class="form-group">
            <label for="email">Email <span class="opt">(optional)</span></label>
            <input type="email" id="email" name="email" autocomplete="email" placeholder="you@example.com">
            <span class="error-msg">Please check this email address.</span>
          </div>
          <div class="form-group">
            <label for="purpose">Purpose of visit <span class="req">*</span></label>
            <select id="purpose" name="purpose" required>
              <option value="">Select a purpose</option>
              <option value="engagement">Engagement / wedding jewellery</option>
              <option value="bridal">Bridal polki &amp; kundan suite</option>
              <option value="custom">Bespoke commission</option>
              <option value="investment">Gold / bullion investment</option>
              <option value="exchange">Old gold exchange or buyback</option>
              <option value="gifting">Gift selection</option>
              <option value="repair">Repair, polishing or restoration</option>
              <option value="valuation">Valuation &amp; certification</option>
            </select>
            <span class="error-msg">Choose the purpose of your visit.</span>
          </div>
        </div>

        <div class="form-row">
          <div class="form-group">
            <label for="date">Preferred date <span class="req">*</span></label>
            <input type="date" id="date" name="date" required>
            <span class="error-msg">Pick a preferred date.</span>
          </div>
          <div class="form-group">
            <label for="time">Preferred time <span class="req">*</span></label>
            <select id="time" name="time" required>
              <option value="">Select a time</option>
              <option value="11:00">11:00 AM</option>
              <option value="12:00">12:00 PM</option>
              <option value="13:00">1:00 PM</option>
              <option value="14:00">2:00 PM</option>
              <option value="15:00">3:00 PM</option>
              <option value="16:00">4:00 PM</option>
              <option value="17:00">5:00 PM</option>
              <option value="18:00">6:00 PM</option>
              <option value="19:00">7:00 PM</option>
              <option value="20:00">8:00 PM</option>
            </select>
            <span class="error-msg">Pick a preferred time.</span>
          </div>
        </div>

        <div class="form-group">
          <label for="message">Budget range &amp; requirements <span class="opt">(optional)</span></label>
          <textarea id="message" name="message" rows="4"
                    placeholder="Tell us the occasion, the design you have in mind, or the weight you are looking for…"></textarea>
        </div>

        <button type="submit" class="btn btn-primary btn-full">
          <span class="btn-text">Request appointment on WhatsApp</span>
          <span class="btn-icon" aria-hidden="true">{ICON['wa']}</span>
        </button>

        <p class="form-note">{ICON['gem']}Your details stay with us. Nothing is shared, and there is no
        obligation to purchase.</p>
        <div class="form-status" id="formStatus" role="status" aria-live="polite"></div>
      </form>
    </div>
  </div>
</section>

<section class="section section--alt">
  <div class="container split split--narrow">
    <div class="prose">
      <h2>Before you come</h2>
      <p class="lede">Three small things that make an appointment go better.</p>
      <ul class="checks">
        <li>{ICON['check']}Bring the person who will wear it, if you can — sizing by proxy is guesswork.</li>
        <li>{ICON['check']}Bring any old gold you want valued. We weigh and test it in front of you, free.</li>
        <li>{ICON['check']}Tell us your budget honestly. It is the fastest way to see the right tray.</li>
      </ul>
    </div>
    <div class="prose">
      <h2>If you cannot visit</h2>
      <p class="lede">We can still help from a distance.</p>
      <ul class="checks">
        <li>{ICON['check']}Send a photograph or sketch on WhatsApp and we will quote it in writing.</li>
        <li>{ICON['check']}Certified stones come with their papers, which we can share before you commit.</li>
        <li>{ICON['check']}Finished pieces are delivered insured, or held at the showroom for collection.</li>
      </ul>
    </div>
  </div>
</section>
</main>
"""
    return page(f"Book an appointment — {SITE['name']}",
                "Book a private viewing at our Gulberg showroom. Fill in the form and we confirm your "
                "slot on WhatsApp within two hours.", "appointment", content)


def page_clients():
    quotes = "".join(testimonial(t, i) + "\n        " for i, t in enumerate(TESTIMONIALS))
    content = f"""<main id="main">
{page_head("Client stories", "Trusted across generations.",
           "Unedited words from brides, collectors and families who have bought from our counter.")}

<section class="section">
  <div class="container">
    <div class="testimonials-grid">
        {quotes}
    </div>
    <div class="collections-foot">
      <p class="collections-note">These are sample quotes held in the site's build file — replace them
      with real, permissioned client words before launch.</p>
    </div>
  </div>
</section>

{cta_band("Come and see for yourself.",
          "Reviews are other people's opinions. The gold under our light is a fact.",
          "appointment.html", "Book an appointment", "collections.html", "Browse the collections")}
</main>
"""
    return page(f"Client stories — {SITE['name']}",
                "What clients say about buying bridal, bespoke and bullion jewellery from us.", "clients", content)


def page_visit():
    content = f"""<main id="main">
{page_head("Visit", "Come and see it in daylight.",
           "Gold always looks different under our light than under anyone else's. "
           "Bring your family — there is tea.")}

<section class="section">
  <div class="container visit-grid">
    <div class="visit-card" data-aos="fade-right">
      <h2>{esc(SITE['name'])}</h2>
      <p>Gulberg III, Lahore &middot; Valet parking available on request</p>

      <dl class="visit-list">
        <div class="visit-row">
          <span class="ico" aria-hidden="true">{ICON['pin']}</span>
          <div>
            <dt>Address</dt>
            <dd>{esc(SITE['address_1'])}<br>{esc(SITE['address_2'])}</dd>
          </div>
        </div>
        <div class="visit-row">
          <span class="ico" aria-hidden="true">{ICON['phone']}</span>
          <div>
            <dt>Telephone &amp; WhatsApp</dt>
            <dd><a href="tel:{SITE['phone_display'].replace(' ', '')}">{esc(SITE['phone_display'])}</a><br>
                <a href="mailto:{SITE['email']}">{esc(SITE['email'])}</a></dd>
          </div>
        </div>
        <div class="visit-row">
          <span class="ico" aria-hidden="true">{ICON['clock']}</span>
          <div>
            <dt>Opening hours</dt>
            <dd>{esc(SITE['hours_week'])}<br>{esc(SITE['hours_sun'])}</dd>
          </div>
        </div>
        <div class="visit-row">
          <span class="ico" aria-hidden="true">{ICON['route']}</span>
          <div>
            <dt>Getting here</dt>
            <dd>Five minutes from Liberty Roundabout, opposite the gold souk arcade. Lift access to the
            first floor.</dd>
          </div>
        </div>
      </dl>

      <a class="btn btn-ghost directions-btn" href="{SITE['maps']}" target="_blank" rel="noopener">
        Get directions {ICON['arrow']}
      </a>
    </div>

    <div class="visit-art" data-aos="fade-left" aria-hidden="true">{motif_dark('bridal')}</div>
  </div>
</section>

<section class="section section--alt">
  <div class="container split split--narrow">
    <div class="prose">
      <h2>Bringing old gold?</h2>
      <p class="lede">We value it while you wait, and show you the scale.</p>
      <ul class="checks">
        <li>{ICON['check']}Cleaning and polishing of pieces bought here is free, any time.</li>
        <li>{ICON['check']}Valuation for insurance or resale is available by appointment.</li>
        <li>{ICON['check']}We will tell you honestly when a repair is worth doing, and when it is not.</li>
      </ul>
    </div>
    <div class="prose">
      <h2>Accessibility</h2>
      <p class="lede">Tell us what you need and we will arrange it before you arrive.</p>
      <ul class="checks">
        <li>{ICON['check']}Lift access and step-free entry from the arcade side.</li>
        <li>{ICON['check']}Seating at the counter, and a private room for longer appointments.</li>
        <li>{ICON['check']}Urdu, Punjabi and English spoken. Sign interpretation on request.</li>
      </ul>
    </div>
  </div>
</section>

{cta_band("Plan your visit.", "Appointments are not required, but they help — especially on Saturdays.",
          "appointment.html", "Book an appointment", wa_general(), "Ask on WhatsApp")}
</main>
"""
    return page(f"Visit the showroom — {SITE['name']}",
                "Address, opening hours, directions and contact details for our showroom in Gulberg III, "
                "Lahore.", "visit", content)


def legal_page(slug, title, crumb, lede, sections, updated="October 2026"):
    body = "".join(f"\n      <h2>{h}</h2>\n      {c}" for h, c in sections)
    note = ('<p class="legal-note">This page is a starting template, not legal advice. Have it reviewed '
            'by a lawyer before you publish it.</p>')
    content = f"""<main id="main">
{page_head(crumb, title, lede)}

<section class="section">
  <div class="container prose prose--legal">
    <p class="updated">Last updated: {updated}</p>{body}
    {note}
  </div>
</section>
</main>
"""
    return page(f"{title} — {SITE['name']}", lede, "", content)


def page_privacy():
    items = [
        ("What we collect",
         "<p>If you book an appointment or enquire about a piece, we receive the details you send us: your "
         "name, phone number, and optionally your email address, the purpose of your visit and any notes "
         "you add. If you subscribe, we hold your email address. Our website does not set advertising "
         "cookies or track you across other sites.</p>"),
        ("Why we hold it",
         "<p>To answer your enquiry, confirm and keep your appointment, and — if you asked for it — to send "
         "occasional updates about new pieces. We also keep the paperwork for a sale because gold and "
         "diamond sales carry legal record-keeping obligations.</p>"),
        ("Who sees it",
         "<p>Your details stay with us. WhatsApp messages are transmitted through WhatsApp and are subject "
         "to their terms; email is transmitted through our email provider. We do not sell, rent or trade "
         "your details to anyone.</p>"),
        ("How long we keep it",
         "<p>Enquiries that do not become a sale are deleted within twelve months. Sale records are kept as "
         "long as the law requires. Newsletter subscriptions are kept until you unsubscribe.</p>"),
        ("Your choices",
         "<p>Write to us and we will show you what we hold about you, correct it, or delete it — except "
         "records we are legally obliged to keep. Unsubscribing takes one click, and we will not ask why.</p>"),
        ("Security",
         "<p>We keep customer records on protected devices and do not carry your details off the premises. "
         "If you would rather not send information electronically, telephone the showroom or bring it "
         "in person.</p>"),
    ]
    return legal_page(
        "privacy", "Privacy Policy", "Privacy",
        "What we collect when you enquire or book with us, why we hold it, and how to have it removed.",
        items)


def page_terms():
    items = [
        ("Prices and the gold rate",
         "<p>Prices shown on this website are indicative and move with the gold rate and stone market. The "
         "price that applies to your purchase is the one we quote and confirm in writing on the day. "
         "Nothing on this website is an offer capable of acceptance.</p>"),
        ("Made-to-order pieces",
         "<p>Commissions are quoted before work begins, and the quote itemises metal, stones and making. "
         "Made-to-order pieces cannot be returned or exchanged, because they are made to your specification; "
         "we therefore agree the design, weight and dimensions with you in writing before we start.</p>"),
        ("Hallmarking and certification",
         "<p>Gold is supplied hallmarked to the standard required for its purity. Where a stone is certified, "
         "the certificate is supplied with the piece. If a certificate is lost, we will help you replace it "
         "at cost.</p>"),
        ("Exchange, buyback and old gold",
         "<p>Exchange and buyback rates are quoted at the time of the transaction and depend on the day's "
         "rate and the condition of the piece. Old gold is weighed and tested in front of you. Pieces bought "
         "from us are bought back on more favourable terms than pieces bought elsewhere; ask us for the "
         "current schedule before you buy.</p>"),
        ("Repairs and servicing",
         "<p>Cleaning and polishing of pieces bought from us is free. Repairs are quoted before work starts. "
         "We are not responsible for damage to a piece that has been repaired elsewhere, or for stones "
         "replaced by another workshop.</p>"),
        ("Delivery and risk",
         "<p>Insured delivery can be arranged within Pakistan; risk passes on delivery to the address you "
         "give us. Pieces held at the showroom for collection are insured by us until you take them.</p>"),
        ("Settling a problem",
         "<p>If something is wrong with a piece we made or sold, tell us first and give us the chance to put "
         "it right. Most issues are resolved at the counter. If we cannot agree, the matter is subject to "
         "the courts of Lahore, Pakistan.</p>"),
    ]
    return legal_page(
        "terms", "Terms of Sale", "Terms",
        "How pricing, made-to-order work, exchange, repairs and delivery operate when you buy from us.",
        items)


def page_piece(p):
    specs = "".join(
        f'\n            <div class="spec"><dt>{esc(k)}</dt><dd>{esc(v)}</dd></div>' for k, v in p["specs"])
    tags = "".join(f'\n            <span class="tag">{esc(t)}</span>' for t in p["tags"])
    metals = " · ".join(METALS[m] for m in p["metals"])
    badge = f'<span class="badge gold">{esc(p["badge"])}</span>' if p.get("badge") else ""
    rel = "".join(card(r, i * 45) + "\n            " for i, r in enumerate(related_to(p)))
    enquire = f"{p['name']}|{p['price']}|piece-{p['id']}.html"

    content = f"""<main id="main">
<header class="page-head page-head--tight">
  <div class="container">
    <nav class="crumb" aria-label="Breadcrumb">
      <a href="index.html">Home</a><span aria-hidden="true">/</span>
      <a href="collections.html">Collections</a><span aria-hidden="true">/</span>
      <span>{esc(p['name'])}</span>
    </nav>
  </div>
</header>

<section class="section section--tight">
  <div class="container piece">
    <div class="piece-media" data-aos="fade-right">
      {badge}
      {product_media(p)}
    </div>

    <div class="piece-body" data-aos="fade-left">
      <p class="piece-eyebrow">{TYPES[p['type']]} · {OCCASIONS[p['occasion']]}</p>
      <h1 class="piece-name">{esc(p['name'])}</h1>
      <p class="piece-lede">{esc(p['story'])}</p>

      <p class="piece-price">{esc(p['price'])}<small>{esc(p['note'])}</small></p>

      <dl class="piece-specs">{specs}
      </dl>

      <div class="piece-tags">{tags}
        <span class="tag">{esc(metals)}</span>
      </div>

      <div class="piece-actions">
        <button class="btn btn-primary" type="button" data-enquire="{esc(enquire)}">
          Enquire on WhatsApp
        </button>
        <a class="btn btn-secondary" href="appointment.html">Book a viewing</a>
      </div>

      <p class="piece-note">Ask us about availability, the exact weight, or to see the certificate
      before you decide.</p>
    </div>
  </div>
</section>

<section class="section section--alt">
  <div class="container">
    <div class="section-header">
      <span class="section-tag">You might also like</span>
      <h2>More from the house.</h2>
    </div>
    <div class="products-grid">
            {rel}
    </div>
  </div>
</section>

{cta_band("See it in person.", "Photographs flatter; daylight does not. Come and hold it.",
          "appointment.html", "Book a viewing", "collections.html", "Back to collections")}
</main>
"""
    return page(f"{p['name']} — {SITE['name']}",
                f"{p['desc']} {TYPES[p['type']]} in {metals}, {p['price']}.",
                "collections", content)


# ---------------------------------------------------------------------------
# 6. BUILD
# ---------------------------------------------------------------------------
def main():
    here = os.path.dirname(os.path.abspath(__file__))
    written = []

    def write(name, contents):
        with open(os.path.join(here, name), "w", encoding="utf-8") as fh:
            fh.write(contents)
        written.append(name)

    write("index.html", page_home())
    write("about.html", page_about())
    write("collections.html", page_collections())
    write("atelier.html", page_atelier())
    write("appointment.html", page_appointment())
    write("clients.html", page_clients())
    write("visit.html", page_visit())
    write("privacy.html", page_privacy())
    write("terms.html", page_terms())
    for p in PRODUCTS:
        write("piece-%s.html" % p["id"], page_piece(p))

    print("built %d pages:" % len(written))
    for name in written:
        print("  ", name)

    if LOGO_FILE:
        print("\nlogo: %s  (%s layout)" % (LOGO_FILE, LOGO_MODE))
        if LOGO_MODE == "lockup":
            print("      the artwork carries the name, so no wordmark text is rendered")
    else:
        print("\nlogo: none in assets/ — using the ALM monogram placeholder")
        print("      drop your file in as assets/logo.svg (or .png/.webp) and rebuild")

    print("hero: %s" % (find_hero_image() or "none — plain dark band"))


if __name__ == "__main__":
    main()
