/* ==========================================================================
   ALIF LAAM MEEM JEWELLERS — Site behaviour
   Vanilla JS, no dependencies. Content is generated by build.py.
   ========================================================================== */
(function () {
  'use strict';

  /* ---------------------------------------------------------------------
     Catalogue content, the header and the footer are generated by build.py.
     This file only handles behaviour, so every page shares one script.
     --------------------------------------------------------------------- */
  const WA_FALLBACK = '923000000000';

  const $  = (sel, ctx) => (ctx || document).querySelector(sel);
  const d$ = (sel, ctx) => (ctx || document).querySelector(sel);
  const $$ = (sel, ctx) => Array.prototype.slice.call((ctx || document).querySelectorAll(sel));

  let WA_NUMBER = WA_FALLBACK;
  const setWaNumber = (n) => { if (n) WA_NUMBER = String(n).replace(/[^\d]/g, ''); };
  const waLink = (msg) =>
    'https://wa.me/' + WA_NUMBER + '?text=' + encodeURIComponent(msg);

  /* ---------------------------------------------------------------------
     2. COLLECTIONS FILTERS
     The catalogue is static HTML built by build.py; filtering shows and hides
     the cards that are already in the page. Everything a filter needs is on
     the card itself: data-type, data-metals, data-occasion.
     --------------------------------------------------------------------- */
  const FILTERS = {
    type: {
      label: 'Type',
      options: { rings: 'Rings', necklace: 'Necklaces', earrings: 'Earrings', bangles: 'Bangles', bridal: 'Bridal sets' },
    },
    metal: {
      label: 'Metal',
      options: { gold22: '22K gold', gold18: '18K gold', rose: 'Rose gold', white: 'White gold', plat: 'Platinum' },
    },
    occasion: {
      label: 'Occasion',
      options: { bridal: 'Bridal', engagement: 'Engagement', festive: 'Festive', everyday: 'Everyday', gifting: 'Gifting', investment: 'Investment' },
    },
  };

  const filterState = { group: 'all', value: null };

  /* Progressive reveal for the catalogue grid: the first REVEAL_BATCH cards
     ship visible, the rest are revealed as the visitor scrolls. Keep in step
     with REVEAL_BATCH in build.py. When a concrete filter is active the whole
     matching set is shown at once — the list is small enough. */
  const REVEAL_BATCH = 6;
  const revealState = { count: REVEAL_BATCH };
  const progressiveActive = () => filterState.value === null;

  function cardMatches(el) {
    if (!filterState.value) return true;
    if (filterState.group === 'type') return el.dataset.type === filterState.value;
    if (filterState.group === 'occasion') return el.dataset.occasion === filterState.value;
    if (filterState.group === 'metal') {
      return (el.dataset.metals || '').split(/\s+/).indexOf(filterState.value) > -1;
    }
    return true;
  }

  function applyFilter() {
    const grid = $('#productsGrid');
    const spotlight = $('#spotlight');
    const empty = $('#noResults');
    const status = $('#filterStatus');
    if (!grid) return;

    const total = $$('.product-card', grid).length + (spotlight ? 1 : 0);
    const prog = progressiveActive();

    let shown = 0;
    $$('.product-card', grid).forEach((el, i) => {
      const ok = cardMatches(el);
      const revealed = !prog || i < revealState.count;
      el.hidden = !(ok && revealed);
      if (ok && revealed) shown++;
    });

    if (spotlight) {
      const ok = cardMatches(spotlight);
      spotlight.hidden = !ok;
      if (ok) shown++;
    }
    if (empty) empty.hidden = shown > 0;

    // Announce the result to screen readers, not just the visual grid.
    if (status) {
      status.textContent = shown === 0
        ? 'No pieces match these filters.'
        : shown === total
          ? 'Showing all ' + total + ' pieces.'
          : 'Showing ' + shown + ' of ' + total + ' pieces.';
    }
  }

  /* ---------------------------------------------------------------------
     2b. PROGRESSIVE REVEAL — more pieces as the visitor scrolls
     --------------------------------------------------------------------- */
  function animateCardIn(el, stagger) {
    el.style.animation = 'none';
    el.style.animationDelay = (stagger * 70) + 'ms';
    void el.offsetWidth; // restart the cardIn animation
    el.style.animation = '';
  }

  function revealMore() {
    const grid = $('#productsGrid');
    if (!grid || !progressiveActive()) return;
    const cards = $$('.product-card', grid);
    const total = cards.length;
    if (revealState.count >= total) return;

    const prev = revealState.count;
    revealState.count = Math.min(prev + REVEAL_BATCH, total);
    applyFilter();

    let stagger = 0;
    cards.forEach((el, i) => {
      if (i >= prev && i < revealState.count && !el.hidden) animateCardIn(el, stagger++);
    });

    updateRevealFoot();

    // The visitor is still at the bottom and there is room — keep filling.
    const foot = $('#revealFoot');
    if (foot && revealState.count < total) {
      const r = foot.getBoundingClientRect();
      if (r.top < window.innerHeight + 400) {
        window.requestAnimationFrame(revealMore);
      }
    }
  }

  function updateRevealFoot() {
    const foot = $('#revealFoot');
    if (!foot) return;
    const status = $('#revealStatus');
    const btn = $('#revealMore');
    if (!progressiveActive()) {
      // A filter is narrowing the list — every match is already on screen.
      foot.hidden = true;
      return;
    }
    const total = $$('.product-card', $('#productsGrid')).length;
    const shown = Math.min(revealState.count, total);
    if (status) {
      status.textContent = shown >= total
        ? 'Showing all ' + total + ' pieces.'
        : 'Showing ' + shown + ' of ' + total + ' pieces — scroll for more.';
    }
    if (btn) btn.hidden = shown >= total;
  }

  function initReveal() {
    const grid = $('#productsGrid');
    const foot = $('#revealFoot');
    const btn = $('#revealMore');
    if (!grid || !foot) return;

    applyFilter();
    updateRevealFoot();

    if (btn) btn.addEventListener('click', revealMore);

    if ('IntersectionObserver' in window) {
      const io = new IntersectionObserver((entries) => {
        entries.forEach((en) => { if (en.isIntersecting) revealMore(); });
      }, { rootMargin: '600px 0px' });
      io.observe(foot);
    } else {
      // Fallback: reveal a batch when the foot gets near the viewport.
      window.addEventListener('scroll', () => {
        const r = foot.getBoundingClientRect();
        if (r.top < window.innerHeight + 600) revealMore();
      }, { passive: true });
    }
  }

  /* ---------------------------------------------------------------------
     2c. DEEP LINK — ?type=rings lands on Collections already filtered
     --------------------------------------------------------------------- */
  function initUrlFilter() {
    const params = new URLSearchParams(window.location.search);
    const type = params.get('type');
    if (!type || FILTERS.type.options[type] === undefined) return;
    const tabs = $$('.filter-tab');
    let typeTab = null;
    tabs.forEach((t) => { if (t.dataset.filter === 'type') typeTab = t; });
    if (!typeTab) return;

    tabs.forEach((t) => {
      const on = t === typeTab;
      t.classList.toggle('active', on);
      t.setAttribute('aria-pressed', on ? 'true' : 'false');
    });
    filterState.group = 'type';
    renderSubFilters('type');
    const wrap = $('#subFilters');
    if (wrap) {
      $$('.chip', wrap).forEach((c) => {
        const on = c.dataset.val === type;
        c.classList.toggle('active', on);
        c.setAttribute('aria-pressed', on ? 'true' : 'false');
      });
    }
    filterState.value = type;
    applyFilter();
    updateRevealFoot();
  }

  function renderSubFilters(group) {
    const wrap = $('#subFilters');
    if (!wrap) return;
    const spec = FILTERS[group];
    const keys = Object.keys(spec.options);
    wrap.innerHTML =
      '<button class="chip active" type="button" aria-pressed="true" data-val="">All</button>' +
      keys.map((k) =>
        '<button class="chip" type="button" aria-pressed="false" data-val="' + k + '">' +
        spec.options[k] + '</button>').join('');
  }

  function initFilters() {
    const tabs = $$('.filter-tab');
    const wrap = $('#subFilters');
    if (!tabs.length) return;

    tabs.forEach((tab) => {
      tab.addEventListener('click', () => {
        tabs.forEach((t) => {
          const on = t === tab;
          t.classList.toggle('active', on);
          t.setAttribute('aria-pressed', on ? 'true' : 'false');
        });
        filterState.group = tab.dataset.filter;
        filterState.value = null;
        if (tab.dataset.filter === 'all') {
          if (wrap) wrap.innerHTML = '';
        } else {
          renderSubFilters(tab.dataset.filter);
        }
        applyFilter();
      });
    });

    if (wrap) {
      wrap.addEventListener('click', (e) => {
        const chip = e.target.closest && e.target.closest('.chip');
        if (!chip) return;
        $$('.chip', wrap).forEach((c) => {
          const on = c === chip;
          c.classList.toggle('active', on);
          c.setAttribute('aria-pressed', on ? 'true' : 'false');
        });
        filterState.value = chip.dataset.val || null;
        applyFilter();
      });
    }
  }

  /* ---------------------------------------------------------------------
     4. QUICK VIEW — every detail of a piece without leaving the page.
     Data comes from the #catalogue-data JSON island (build.py), so opening
     details never fetches anything.
     --------------------------------------------------------------------- */
  const CATALOGUE = (function () {
    const el = d$('#catalogue-data');
    if (!el) return null;
    try { return JSON.parse(el.textContent); } catch (e) { return null; }
  })();

  let qvLastTrigger = null;

  function qvOpen(item) {
    let overlay = d$('.qv-overlay');
    if (!overlay) {
      overlay = document.createElement('div');
      overlay.className = 'qv-overlay';
      overlay.innerHTML =
        '<div class="qv-panel" role="dialog" aria-modal="true" aria-labelledby="qvName">' +
          '<button class="qv-close" type="button" aria-label="Close details">' +
            '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">' +
            '<path d="M6 6l12 12M18 6L6 18"/></svg>' +
          '</button>' +
          '<div class="qv-media"></div>' +
          '<div class="qv-body"></div>' +
        '</div>';
      document.body.appendChild(overlay);
      overlay.addEventListener('click', (e) => { if (e.target === overlay) qvClose(); });
      d$('.qv-close', overlay).addEventListener('click', qvClose);
    }

    const badgeCls = (item.badge === 'Bestseller' || item.badge === 'Signature') ? 'badge gold' : 'badge';
    const badge = item.badge ? '<span class="' + badgeCls + '">' + item.badge + '</span>' : '';
    const media = item.photo
      ? '<img class="product-photo" src="' + item.photo + '" alt="' + item.name + '">'
      : (CATALOGUE.motifs[item.motif] || '');
    d$('.qv-media', overlay).innerHTML = badge + media;

    const specs = item.specs.map((s) =>
      '<div class="spec"><dt>' + s[0] + '</dt><dd>' + s[1] + '</dd></div>').join('');
    const tags = item.tags.map((t) => '<span class="tag">' + t + '</span>').join('') +
      '<span class="tag">' + item.metals.join(' · ') + '</span>';

    d$('.qv-body', overlay).innerHTML =
      '<p class="qv-eyebrow">' + CATALOGUE.types[item.type] + ' · ' + CATALOGUE.occasions[item.occasion] + '</p>' +
      '<h2 class="qv-name" id="qvName">' + item.name + '</h2>' +
      '<p class="qv-price">' + item.price + '<small>' + item.note + '</small></p>' +
      '<p class="qv-desc">' + item.desc + '</p>' +
      '<p class="qv-story">' + item.story + '</p>' +
      '<h3 class="qv-sub">Specifications</h3>' +
      '<dl class="qv-specs">' + specs + '</dl>' +
      '<div class="qv-tags">' + tags + '</div>' +
      '<div class="qv-actions">' +
        '<button class="btn btn-primary" type="button" data-enquire="' + item.name + '|' + item.price + '|' + item.href + '">Enquire on WhatsApp</button>' +
        '<a class="btn btn-secondary" href="appointment.html">Book a viewing</a>' +
        '<a class="qv-full" href="' + item.href + '">Open the full page</a>' +
      '</div>';

    overlay.hidden = false;
    document.body.classList.add('no-scroll');
    window.requestAnimationFrame(() => overlay.classList.add('open'));
    d$('.qv-close', overlay).focus();

    document.removeEventListener('keydown', qvKeyHandler);
    document.addEventListener('keydown', qvKeyHandler);
  }

  function qvClose() {
    const overlay = d$('.qv-overlay');
    if (!overlay) return;
    overlay.classList.remove('open');
    document.body.classList.remove('no-scroll');
    document.removeEventListener('keydown', qvKeyHandler);
    window.setTimeout(() => { overlay.hidden = true; }, 260);
    if (qvLastTrigger && document.contains(qvLastTrigger)) qvLastTrigger.focus();
    qvLastTrigger = null;
  }

  function qvKeyHandler(e) {
    const overlay = d$('.qv-overlay');
    if (!overlay) return;
    if (e.key === 'Escape') { qvClose(); return; }
    if (e.key === 'Tab') {
      // Keep focus inside the dialog while it is open.
      const focusables = $$('button, a[href]', overlay);
      if (!focusables.length) return;
      const first = focusables[0];
      const last = focusables[focusables.length - 1];
      if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); }
      else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); }
    }
  }

  function initQuickView() {
    if (!CATALOGUE) return;
    document.addEventListener('click', (e) => {
      const trigger = e.target.closest ? e.target.closest('[data-quickview]') : null;
      if (!trigger) return;
      let item = null;
      CATALOGUE.items.forEach((i) => { if (i.id === trigger.dataset.quickview) item = i; });
      if (!item) return;
      qvLastTrigger = trigger;
      qvOpen(item);
    });
  }

  /* ---------------------------------------------------------------------
     6. RENDER: testimonials
     --------------------------------------------------------------------- */
  /* ---------------------------------------------------------------------
     7. APPOINTMENT FORM → WhatsApp
     --------------------------------------------------------------------- */
  function initForm() {
    const form = $('#appointmentForm');
    if (!form) return;
    setWaNumber(form.dataset.waNumber);
    const SHOP = form.dataset.waName || 'the showroom';

    const dateInput = $('#date');
    if (dateInput) {
      const today = new Date();
      const iso = new Date(today.getTime() - today.getTimezoneOffset() * 60000)
        .toISOString().slice(0, 10);
      dateInput.min = iso;
      dateInput.value = '';
    }

    const status = $('#formStatus');

    function setInvalid(field, on, msg) {
      const group = field.closest('.form-group');
      if (!group) return;
      group.classList.toggle('invalid', on);

      // Keep the message tied to the field for screen readers, not just visually.
      const box = $('.error-msg', group);
      let described = [];
      if (box) {
        if (!box.id) box.id = (field.id || field.name || 'field') + '-error';
        if (msg) box.textContent = msg;
        const ids = (field.getAttribute('aria-describedby') || '').split(/\s+/).filter(Boolean);
        const at = ids.indexOf(box.id);
        if (on && at === -1) ids.push(box.id);
        if (!on && at > -1) ids.splice(at, 1);
        described = ids;
      }
      if (described.length) field.setAttribute('aria-describedby', described.join(' '));
      else field.removeAttribute('aria-describedby');

      if (on) field.setAttribute('aria-invalid', 'true');
      else field.removeAttribute('aria-invalid');
    }

    $$('input, select, textarea', form).forEach((f) => {
      f.addEventListener('input', () => setInvalid(f, false));
      f.addEventListener('change', () => setInvalid(f, false));
    });

    form.addEventListener('submit', (e) => {
      e.preventDefault();

      const name = $('#name');
      const phone = $('#phone');
      const purpose = $('#purpose');
      const date = $('#date');
      const time = $('#time');
      let firstBad = null;

      const checks = [
        [name, name.value.trim().length >= 3, 'Please enter your full name.'],
        [phone, /^[+()\-\s\d]{9,20}$/.test(phone.value.trim()), 'Enter a reachable phone number.'],
        [purpose, !!purpose.value, 'Choose the purpose of your visit.'],
        [date, !!date.value, 'Pick a preferred date.'],
        [time, !!time.value, 'Pick a preferred time.']
      ];

      checks.forEach(([field, ok, msg]) => {
        setInvalid(field, !ok, msg);
        if (!ok && !firstBad) firstBad = field;
      });

      if (firstBad) {
        const bad = checks.filter((c) => !c[1]).length;
        if (status) {
          status.innerHTML = '<span>' + bad +
            (bad === 1 ? ' field needs' : ' fields need') +
            ' your attention before we can prepare the request.</span>';
          status.classList.add('show');
        }
        firstBad.focus();
        return;
      }

      const lines = [
        'Assalam-o-Alaikum, ' + SHOP + '.',
        '',
        'I would like to book a showroom consultation.',
        '',
        'Name: ' + name.value.trim(),
        'Phone: ' + phone.value.trim()
      ];
      const email = $('#email');
      const message = $('#message');
      if (email && email.value.trim()) lines.push('Email: ' + email.value.trim());
      lines.push('Purpose: ' + purpose.options[purpose.selectedIndex].text);
      lines.push('Preferred date: ' + date.value);
      lines.push('Preferred time: ' + time.options[time.selectedIndex].text);
      if (message && message.value.trim()) lines.push('Notes: ' + message.value.trim());

      const msg = lines.join('\n');
      const hidden = $('#whatsappMessage');
      if (hidden) hidden.value = msg;

      window.open(waLink(msg), '_blank', 'noopener');

      if (status) {
        status.innerHTML =
          '<svg class="tick" viewBox="0 0 24 24" fill="none" stroke="currentColor" ' +
          'stroke-width="1.8" aria-hidden="true"><circle cx="12" cy="12" r="10"/>' +
          '<path d="M7.5 12.4l3 3 6-6.4"/></svg>' +
          '<span>Thank you, ' + name.value.trim().split(' ')[0] +
          ' — your request has been prepared in WhatsApp. Send the message and ' +
          'we will confirm your slot within 2 hours.</span>';
        status.classList.add('show');
      }
    });
  }

  /* ---------------------------------------------------------------------
     8. NEWSLETTER + wishlist micro-interactions
     --------------------------------------------------------------------- */
  function initNewsletter() {
    const form = $('#newsletterForm');
    if (!form) return;
    form.addEventListener('submit', (e) => {
      e.preventDefault();
      const input = $('input', form);
      const msg = $('#newsletterMsg');
      if (!input || !input.value.trim()) return;
      if (msg) {
        msg.textContent = 'Added ' + input.value.trim() +
          ' — we will send the new arrivals preview, never more than twice a month.';
        msg.classList.add('show');
      }
      form.reset();
    });
  }

  function initDelegatedClicks() {
    document.addEventListener('click', (e) => {
      const fav = e.target.closest('[data-fav]');
      if (fav) {
        const on = fav.getAttribute('aria-pressed') === 'true';
        fav.setAttribute('aria-pressed', on ? 'false' : 'true');
        fav.classList.toggle('active', !on);
        return;
      }
      const enq = e.target.closest('[data-enquire]');
      if (enq) {
        const parts = enq.dataset.enquire.split('|');
        const msg = 'Assalam-o-Alaikum.\n\n' +
          'I am interested in: ' + parts[0] + (parts[1] ? ' (' + parts[1] + ')' : '') + '\n' +
          'Could you share availability, weight and current pricing?';
        window.open(waLink(msg), '_blank', 'noopener');
      }
    });
  }

  /* ---------------------------------------------------------------------
     9. NAV, SCROLL, REVEAL, COUNTERS
     --------------------------------------------------------------------- */
  function initNav() {
    const nav = $('#navbar');
    const btn = $('#mobileMenuBtn');
    const links = $('#navLinks');

    const onScroll = () => {
      if (nav) nav.classList.toggle('is-stuck', window.scrollY > 12);
      const bar = $('#progress');
      if (bar) {
        const h = document.documentElement.scrollHeight - window.innerHeight;
        bar.style.transform = 'scaleX(' + (h > 0 ? Math.min(window.scrollY / h, 1) : 0) + ')';
      }
      const top = $('#backToTop');
      if (top) {
        const show = window.scrollY > 620;
        top.classList.toggle('show', show);
        top.setAttribute('aria-hidden', show ? 'false' : 'true');
      }
    };
    window.addEventListener('scroll', onScroll, { passive: true });
    onScroll();

    if (btn && links) {
      const setMenu = (open) => {
        btn.setAttribute('aria-expanded', open ? 'true' : 'false');
        links.classList.toggle('open', open);
        document.body.classList.toggle('no-scroll', open);
      };
      btn.addEventListener('click', () =>
        setMenu(btn.getAttribute('aria-expanded') !== 'true'));
      $$('.nav-link', links).forEach((a) =>
        a.addEventListener('click', () => setMenu(false)));
      document.addEventListener('keydown', (e) => {
        if (e.key === 'Escape' && links.classList.contains('open')) {
          setMenu(false);
          btn.focus();
        }
      });
      window.addEventListener('resize', () => {
        // Matches the CSS breakpoint where the desktop nav takes over.
        if (window.innerWidth > 860 && links.classList.contains('open')) setMenu(false);
      });
    }

    const top = $('#backToTop');
    if (top) {
      top.addEventListener('click', () =>
        window.scrollTo({ top: 0, behavior: 'smooth' }));
    }

    // Active link highlight
    const sections = $$('section[id]');
    const navAs = $$('.nav-link[href^="#"]');
    if ('IntersectionObserver' in window && sections.length) {
      const spy = new IntersectionObserver((entries) => {
        entries.forEach((entry) => {
          if (!entry.isIntersecting) return;
          const id = entry.target.id;
          navAs.forEach((a) =>
            a.classList.toggle('active', a.getAttribute('href') === '#' + id));
        });
      }, { rootMargin: '-45% 0px -50% 0px', threshold: 0 });
      sections.forEach((s) => spy.observe(s));
    }
  }

  /* ---------------------------------------------------------------------
     9b. PAGE INTRO
     A brief branded curtain on first paint, then the hero resolves in
     sequence. The markup is hidden pre-paint by .intro-on on <html>, so
     nothing flashes before this runs. Reveal animations start only after
     the hero has finished resolving — otherwise the two race each other.
     --------------------------------------------------------------------- */
  function initIntro() {
    const intro = $('#intro');
    const hero = $('.intro-wrap');

    if (reduceMotion()) {
      if (intro) intro.remove();
      if (hero) hero.classList.add('intro-open');
      initReveal();
      return;
    }

    let done = false;
    const finish = () => {
      if (done) return;
      done = true;
      if (hero) hero.classList.add('intro-open');
      if (intro) intro.classList.add('is-done');
      document.body.classList.remove('intro-lock');
      window.setTimeout(() => { if (intro && intro.parentNode) intro.remove(); }, 640);
      window.setTimeout(initReveal, 160);
    };

    document.body.classList.add('intro-lock');

    if (document.readyState === 'complete') {
      window.setTimeout(finish, 780);
    } else {
      window.addEventListener('load', () => window.setTimeout(finish, 780), { once: true });
      // if the load event never lands (slow font/asset stall), do not trap the page
      window.setTimeout(finish, 2800);
    }
  }

  function initReveal() {
    const items = $$('[data-aos]');
    if (!items.length) return;
    if (!('IntersectionObserver' in window)) {
      items.forEach((el) => el.classList.add('aos-in'));
      return;
    }
    const io = new IntersectionObserver((entries, obs) => {
      entries.forEach((entry) => {
        if (!entry.isIntersecting) return;
        const el = entry.target;
        const delay = el.dataset.aosDelay ? parseInt(el.dataset.aosDelay, 10) : 0;
        el.style.transitionDelay = delay + 'ms';
        el.classList.add('aos-in');
        obs.unobserve(el);
      });
    }, { rootMargin: '0px 0px -8% 0px', threshold: 0.12 });
    items.forEach((el) => io.observe(el));
  }

  function initCounters() {
    const nums = $$('[data-count]');
    if (!nums.length) return;
    const reduce = !!window.matchMedia &&
      window.matchMedia('(prefers-reduced-motion: reduce)').matches;

    const run = (el) => {
      const target = parseFloat(el.dataset.count);
      const suffix = el.dataset.suffix || '';
      const decimals = (el.dataset.count.split('.')[1] || '').length;
      if (reduce) { el.textContent = target.toFixed(decimals) + suffix; return; }
      const dur = 1500;
      const start = performance.now();
      const tick = (now) => {
        const t = Math.min((now - start) / dur, 1);
        const eased = 1 - Math.pow(1 - t, 3);
        el.textContent = (target * eased).toFixed(decimals) + suffix;
        if (t < 1) requestAnimationFrame(tick);
      };
      requestAnimationFrame(tick);
    };

    if (!('IntersectionObserver' in window)) { nums.forEach(run); return; }
    const io = new IntersectionObserver((entries, obs) => {
      entries.forEach((entry) => {
        if (!entry.isIntersecting) return;
        run(entry.target);
        obs.unobserve(entry.target);
      });
    }, { threshold: 0.5 });
    nums.forEach((el) => io.observe(el));
  }

  function reduceMotion() {
    return !!window.matchMedia &&
      window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  }

  function hydrateSite() {
    // the WhatsApp number lives on the form, so build.py stays the single source
    const form = $('#appointmentForm');
    if (form) setWaNumber(form.dataset.waNumber);

    // keep the copyright year current without rebuilding the site
    const y = $('#year');
    if (y) y.textContent = new Date().getFullYear();
  }

  /* ---------------------------------------------------------------------
     10. BOOT
     --------------------------------------------------------------------- */
  function init() {
    hydrateSite();
    initFilters();
    initUrlFilter();
    initReveal();
    initQuickView();
    initForm();
    initNewsletter();
    initDelegatedClicks();
    initNav();
    initIntro();
    initCounters();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
